es-app/src/guis/GuiGamelistOptions.cpp
es-app/src/views/gamelist/BasicGameListView.cpp
es-app/src/views/gamelist/BasicGameListView.h
es-app/src/views/gamelist/IGameListView.h

Moved rom deletion to gamelist, fixed halt on removal.

---

es-core/src/Renderer_init_sdlgl.cpp

Since I have been doing some cosmetic changes - this is a minor improvement to avoid the flash of the mouse pointer

Hide mouse cursor early

---

es-app/src/SystemData.cpp
es-app/src/SystemData.h
es-app/src/views/SystemView.cpp
es-app/src/views/ViewController.cpp
es-app/src/views/gamelist/BasicGameListView.cpp

Reverts RetroPie/EmulationStation#1

Revert "Add direct launch option for systems that don't need a game list"

---

es-core/src/InputManager.cpp
es-core/src/InputManager.h

Reverts RetroPie/EmulationStation#58
Causes problems with dpad on 8bitdo controller - will need to revisit.

Revert "workaround for analogue trigger configuration - eg with xpad."

---

es-app/src/main.cpp
es-core/src/Settings.cpp

no splash option for ES from Herdinger's fork

Added a --no-splash option for disabling the ES logo

---

THEMES.md

add documentation for video view and video element.

add video documentation

---

es-app/src/scrapers/GamesDBScraper.cpp

Fixes platform name for Neo Geo so that the scraper works

Fix for Neo Geo games not being scraped - Update GamesDBScraper.cpp

---

es-core/src/components/TextEditComponent.cpp

This fixes the initial text position (eventually by keeping mScrollOffset.x() at 0 after constructor) and makes it understand more keyboard keys: cursor left/right, home, end, delete.
Don't like the implementation for delete but it works...
Hope this is of some use.

Improved TextEditComponent

---

es-app/src/views/SystemView.cpp
es-core/src/components/TextComponent.cpp
es-core/src/components/TextComponent.h

fix black boxes appearing on gamelist after scrolling

---

es-app/CMakeLists.txt
es-app/src/FileData.cpp
es-app/src/FileData.h
es-app/src/FileFilterIndex.cpp
es-app/src/FileFilterIndex.h
es-app/src/Gamelist.cpp
es-app/src/SystemData.cpp
es-app/src/SystemData.h
es-app/src/guis/GuiGamelistFilter.cpp
es-app/src/guis/GuiGamelistFilter.h
es-app/src/guis/GuiGamelistOptions.cpp
es-app/src/guis/GuiGamelistOptions.h
es-app/src/guis/GuiMetaDataEd.cpp
es-app/src/views/ViewController.cpp
es-app/src/views/gamelist/BasicGameListView.cpp
es-app/src/views/gamelist/GridGameListView.cpp
es-app/src/views/gamelist/ISimpleGameListView.cpp
es-app/src/views/gamelist/VideoGameListView.cpp
es-core/src/components/ComponentList.cpp
es-core/src/components/OptionListComponent.h

Specifically filters for genre, players, ratings and publisher/developer.
Made it fairly generic in order to accommodate any metadata rearchitecture, or Zigurana's kid-friendly/favorites changes.
Rebased with current ES from RetroPie. Hope it suits!

Adding generic gamelist filter funcionality for ES

---

es-app/CMakeLists.txt
es-app/src/FileData.cpp
es-app/src/FileData.h
es-app/src/FileFilterIndex.cpp
es-app/src/FileFilterIndex.h
es-app/src/Gamelist.cpp
es-app/src/SystemData.cpp
es-app/src/SystemData.h
es-app/src/guis/GuiGamelistFilter.cpp
es-app/src/guis/GuiGamelistFilter.h
es-app/src/guis/GuiGamelistOptions.cpp
es-app/src/guis/GuiGamelistOptions.h
es-app/src/guis/GuiMetaDataEd.cpp
es-app/src/views/ViewController.cpp
es-app/src/views/gamelist/BasicGameListView.cpp
es-app/src/views/gamelist/ISimpleGameListView.cpp
es-app/src/views/gamelist/VideoGameListView.cpp
es-core/src/components/ComponentList.cpp
es-core/src/components/OptionListComponent.h

All of the changes here should only be whitespace and indentation related. Fixing mess created in previous PR #115 .
Edit: 1 min, squashing.

Fixing whitespaces and indentation (tabs)

---

es-app/src/views/SystemView.cpp

This modifies the rendering of the extras for system view so that the slide transition slide vertically when using a vertical carousel.

slide transition will slide vertically for vertical carousel

---

es-app/src/views/gamelist/DetailedGameListView.cpp

fix default z-index values for metadata fields on detail view

---

es-app/src/guis/GuiGamelistOptions.cpp
es-app/src/guis/GuiGamelistOptions.h
es-app/src/guis/GuiMenu.cpp
es-app/src/guis/GuiMenu.h
es-app/src/guis/GuiSettings.cpp
es-app/src/guis/GuiSettings.h

Implement a consistent HelpStyle for Menu and Options dialogs to fix #144

Consistent helpstyle

---

es-app/src/guis/GuiMenu.cpp
es-app/src/views/SystemView.cpp
es-app/src/views/ViewController.cpp

Added None and Instant Transitions

Additional transitions

---

THEMES.md
es-app/src/components/TextListComponent.h
es-core/src/ThemeData.cpp

Fixes for issue highlighted here: https://retropie.org.uk/forum/topic/10435/long-standing-es-bugs/46
Also implemented image support for selector bar.

fixes for gamelist bugs; added option to specify image for selctor bar

---

es-app/src/guis/GuiMenu.cpp
es-app/src/views/SystemView.cpp
es-app/src/views/ViewController.cpp
es-core/src/Settings.cpp

- Removed Simple Slide
- Added Switch to control Carousel transition

Move Carousel transition to separate switch

---

es-app/src/views/gamelist/VideoGameListView.cpp

Fix for lack of zoom transition on video view for systems without marquees

---

es-app/src/VolumeControl.cpp
es-core/src/Window.cpp
es-core/src/animations/LambdaAnimation.h
es-core/src/components/ComponentGrid.cpp
es-core/src/components/ComponentList.cpp
es-core/src/guis/GuiInputConfig.cpp

From [the coverity report](https://scan.coverity.com/projects/emulationstation?tab=overview).

various code fixes

---

es-app/src/SystemScreenSaver.cpp
es-app/src/guis/GuiGameScraper.cpp
es-app/src/guis/GuiScraperMulti.cpp
es-app/src/main.cpp
es-core/src/PowerSaver.cpp
es-core/src/PowerSaver.h
es-core/src/Settings.cpp
es-core/src/components/VideoComponent.cpp
es-core/src/components/VideoVlcComponent.cpp

- Video Screensaver to skip fade in/out if Instant
- Video Previews to skip fade in/out if Instant
- Added Pause/Resume methods to PS for better description
- Added basic documentation to PS header file
- Added trailing after waking up from SS
- Added proper timing offsets after PS is triggered
- PS set to Disabled by default
- some whitespace edits

Fixes screensaver not getting triggered

---

es-app/src/CollectionSystemManager.cpp
es-app/src/CollectionSystemManager.h
es-app/src/FileData.cpp
es-app/src/FileData.h
es-app/src/FileFilterIndex.cpp
es-app/src/FileFilterIndex.h
es-app/src/SystemData.cpp
es-app/src/guis/GuiCollectionSystemsOptions.cpp
es-app/src/guis/GuiCollectionSystemsOptions.h
es-app/src/guis/GuiGamelistOptions.cpp
es-app/src/guis/GuiGamelistOptions.h
es-app/src/guis/GuiMenu.cpp
es-app/src/guis/GuiMetaDataEd.cpp
es-app/src/main.cpp
es-app/src/views/ViewController.cpp
es-app/src/views/ViewController.h
es-app/src/views/gamelist/BasicGameListView.cpp
es-app/src/views/gamelist/ISimpleGameListView.cpp
es-core/src/Settings.cpp
es-core/src/Util.cpp
es-core/src/Util.h

Summary of PR:
This is part 2 of the "Game Collections" effort. In particular, this allows users to create a new collection, either from an unused theme folder name (i.e. "neogeo", "capcom", whatever) or by specifying their own name. 
In terms of options:
- Users can choose to keep all custom collections at the top/system level (relying on jrassa's default theme changes), or bundle any collections for which no folder with the same name has been found under the "Collections" system, as sub-folders.
- Users can then choose to keep the normal sorting (current ES_systems ones, and then the new ones), or sort all systems together, in which case it'll sort them all alphabetically, and keep "RetroPie" and the 4 automatic ones at the end. 
Compared to the first PR, I refactored runtime collection …

Added support for custom Game Collection creation

---

CMakeLists.txt

Fallback to Broadcom/MALI autodetect or OpenGL Desktop if no option is selected.

Add options for GL and GLES selection

---

es-app/src/views/ViewController.cpp

Fixes #217 
- Moved Input lock disabling to callback
Ready to merge

Fixes blank screen on key press while exiting game

---

es-app/src/SystemScreenSaver.cpp
es-app/src/SystemScreenSaver.h
es-app/src/guis/GuiScreensaverOptions.cpp
es-core/src/PowerSaver.cpp
es-core/src/PowerSaver.h
es-core/src/Settings.cpp
es-core/src/components/VideoComponent.cpp

This adds a slider to control the swap time for the video screensaver videos.

Adding slider to control screensaver swap time

---

es-app/src/guis/GuiMetaDataEd.cpp
es-core/src/components/MenuComponent.cpp

Made changes to make Menu width dependent on lesser of the two dimensions.

Better handle Menu width

---

es-core/src/PowerSaver.cpp
es-core/src/PowerSaver.h

Disable PS when swap timeout less than PS mode

---

es-core/src/components/IList.h
es-core/src/guis/GuiDetectDevice.cpp

Fixes #243 
@pjft @psyke83 Please check if this is working for your controllers

Handle longclick in PS:Instant mode

---

README.md
es-app/src/guis/GuiGamelistOptions.cpp
es-app/src/guis/GuiMenu.cpp
es-app/src/guis/GuiMenu.h
es-app/src/main.cpp
es-app/src/views/ViewController.cpp
es-app/src/views/ViewController.h
es-core/src/Settings.cpp
es-core/src/Window.cpp
es-core/src/Window.h

Hi!
This is the first part of introducing Kid / Kiosk mode into the RetroPie master branch for Emulationstation.
This PR introduces the hiding of menu items depending on the current UI mode. The second part will focus on hiding actual game-items. 
With this change, you can set the UI mode to "Full" (no changes), or "Kiosk" which will hide all menu items that can potentially alter the system configuration.
These include:
* In the start / GuiMenu: All items except for the "Quit" menu, which only contains the "shutdown system" option.
* In the select / GamelistOptions: the CustomCollection menus, and Edit Metadata
As was the case with the previous implementation, unlocking the protected mode (Kiosk), is done by inputting the konami cheat code (up, up, down, down, left, right, left, right, b, …

Introducing Kiosk Mode, hiding certain menu items from the UI.

---

THEMES.md
es-app/src/views/SystemView.cpp
es-core/src/ThemeData.cpp
es-core/src/components/ImageComponent.cpp
es-core/src/components/ImageComponent.h

Discussed [here](https://retropie.org.uk/forum/topic/7156/variable-support-in-themes-in-emulationstation/62) in the forums.

add support for default image path in themes

---

es-app/src/main.cpp

Just a minor addition of FreeImage_Initialize() and FreeImage_Deinitialize() when using FreeImage as a static library

Support FreeImage as a static library

---

es-app/src/FileData.cpp
es-app/src/FileData.h
es-app/src/views/gamelist/DetailedGameListView.cpp
es-app/src/views/gamelist/VideoGameListView.cpp

try to set default game art ( image and video ) from romfolder/images if the gamelist didn't specify an image or video

Use local game art

---

es-core/src/Renderer_init_sdlgl.cpp

Fix vsync off, SDL_GL_SetSwapInterval(0) is not always default

Fix vsync off

---

es-app/src/SystemData.cpp
es-app/src/main.cpp

Adds support to check if a file is hidden on windows as well.

Add windows support to isHidden

---

es-app/src/guis/GuiMenu.cpp
es-app/src/views/ViewController.cpp
es-core/src/Settings.cpp

Alow to select a system to go directly to the game list (Fixes #253)

---

es-app/src/SystemData.cpp
es-app/src/guis/GuiGamelistFilter.cpp
es-app/src/main.cpp
es-app/src/scrapers/Scraper.cpp
es-core/src/HttpReq.cpp
es-core/src/ImageIO.cpp
es-core/src/ThemeData.cpp
es-core/src/components/ComponentList.cpp
es-core/src/components/ImageGridComponent.h
es-core/src/resources/Font.cpp
es-core/src/resources/TextureDataManager.cpp

Fix a couple of warnings on Windows and Ubuntu, mostly deleting unused variables.

Fix warnings

---

es-core/src/components/VideoPlayerComponent.cpp

Needed to fix build on Pi after https://github.com/RetroPie/EmulationStation/pull/263.
pinging @tomaz82

Implement missed inhouse vector replacements

---

es-core/src/guis/GuiDetectDevice.h

Missed one comment on the header guards.

Fix #endif comment

---

es-app/src/guis/GuiGamelistOptions.cpp

(such as when UIMODE != FULL).
The list of characters now only contains those actually present in the current gamelistview.
Also add support for numbers and some symbols.
See https://retropie.org.uk/forum/topic/12602/kids-kiosk-mode-coming-back-testers-needed/56, for some discussion.

Allow JUMP TO...  in case of filtered lists

---

es-app/src/CollectionSystemManager.cpp
es-app/src/Gamelist.cpp
es-app/src/MetaData.cpp
es-app/src/MetaData.h
es-app/src/SystemData.cpp
es-app/src/SystemScreenSaver.cpp
es-app/src/scrapers/GamesDBScraper.cpp
es-core/src/InputConfig.cpp
es-core/src/InputConfig.h
es-core/src/InputManager.cpp
es-core/src/ThemeData.cpp
es-core/src/ThemeData.h

Exactly what the title says :)

Clean up pugixml.hpp includes

---

es-core/src/math/Misc.h
es-core/src/math/Transform4x4f.h
es-core/src/math/Vector2f.cpp
es-core/src/math/Vector2f.h
es-core/src/math/Vector2i.h
es-core/src/math/Vector3f.cpp
es-core/src/math/Vector3f.h
es-core/src/math/Vector4f.cpp
es-core/src/math/Vector4f.h
es-core/src/utils/FileSystemUtil.cpp
es-core/src/utils/FileSystemUtil.h
es-core/src/utils/StringUtil.cpp
es-core/src/utils/StringUtil.h

These are all classes I wrote and maintain, so I *upgraded* them to follow the way I prefer code so I can more easely have an overview of what I'm doing, also includes renaming some functions with more sensible names. And I need these changes before I can finish the boost cleanup.

Cleanup a couple of classes

---

CMakeLists.txt
es-core/src/CECInput.cpp
es-core/src/CECInput.h
es-core/src/InputConfig.cpp
es-core/src/InputConfig.h
es-core/src/guis/GuiInputConfig.cpp

Log everything CEC does

---

es-app/src/CollectionSystemManager.cpp
es-app/src/FileData.cpp
es-app/src/FileFilterIndex.cpp
es-app/src/views/UIModeController.h
es-core/src/ThemeData.cpp
es-core/src/ThemeData.h
es-core/src/Util.cpp
es-core/src/components/VideoPlayerComponent.cpp
es-core/src/utils/StringUtil.cpp
es-core/src/utils/StringUtil.h

Eliminated the need for boost::xpressive, boost::algorithm and boost::variant

Eliminate some boost usage

---

es-app/src/CollectionSystemManager.cpp
es-app/src/FileData.cpp
es-app/src/FileData.h
es-app/src/Gamelist.cpp
es-app/src/MetaData.cpp
es-app/src/SystemData.cpp
es-app/src/main.cpp
es-core/src/InputManager.cpp
es-core/src/ThemeData.cpp
es-core/src/Util.cpp
es-core/src/guis/GuiDetectDevice.cpp
es-core/src/resources/ResourceManager.cpp
es-core/src/utils/FileSystemUtil.cpp
es-core/src/utils/FileSystemUtil.h
es-core/src/utils/StringUtil.cpp
es-core/src/utils/StringUtil.h
es-core/src/utils/TimeUtil.cpp

This PR basically does 2 things, but mainly, it doesn't actually do anything to ES, yet... it just prepares ES for a heart, brain and spine transplant.
* it adds everything needed to exterminate the last traces of boost in ES, which is boost::filesystem
* it removes all namespace fs = boost::filesystem, which isn't really needed but helps with the next step in my master plan
The coming pieces after this will be split into multiple PR's due to the shear amount of code that will be touched

Utils::FileSystem

---

es-app/src/CollectionSystemManager.cpp
es-app/src/FileSorts.cpp
es-app/src/guis/GuiFastSelect.cpp
es-app/src/guis/GuiFastSelect.h
es-core/src/CECInput.cpp

Just a couple minor fixes and warning silencers

Silence warnings

---

es-app/src/scrapers/GamesDBScraper.cpp

fix platform name for game and watch

---

README.md

Adding some command to compile EmulationStation on Fedora 27

Update instructions for Fedora compilation

---

README.md

Fix the Fedora instructions

---

es-app/src/CollectionSystemManager.cpp

Fix crash when scraping folders, introduced when adding support for collections.

Fix crash when scraping folders

---

es-app/src/SystemData.cpp

Someone left a Smurf in the code (#361)

Remove leftover debug code

---

THEMES.md
es-core/src/ThemeData.cpp
es-core/src/components/ImageGridComponent.h

Vertical by default, but can be set to horizontal by the theme

Add scroll direction to the grid

---

es-core/src/components/ImageGridComponent.h

**Short description**
This is a big clean of the ImageGridComponent code, so it now have a strong, clear and reliable structure for further developments.
**Full changes**
- Separated private methods and attributes in 3 groups :
- images & entries
- tiles
- miscellaneous
- Renamed some methods :
- buildImages -> buildTiles
- updateImages -> updateTiles
- Moved private methods implementation so they respect the same order as their declaration
- Changed some methods internal variable names and other smalls clean

Clean ImageGridComponent code

---

es-app/src/views/gamelist/DetailedGameListView.cpp
es-app/src/views/gamelist/GridGameListView.cpp
es-app/src/views/gamelist/VideoGameListView.cpp

When scrolling at fastest speed for example.

Fix md_name not fading out

---

es-core/src/components/ImageGridComponent.h

This is part of my work in making the ImageGridComponent and its parent the IList more reliables. This make sure the functions "buildTiles" and "calcGridDimension" are only called one time and only when needed (after a theme changed).
**Changes**
- This changes make sure the buildTiles function is called only one time, at the end of the applyTheme function.
- The buildTiles function now call calcGridDimension as both are linked to the same events

Change grid creation flow

---

es-core/src/components/ImageGridComponent.h

- Also fix 2 bugs introduced by #428
- Also add log error message if grid dimensions are below 1

Partially display the last row if grid number of row isn't an integer

---

es-app/src/FileFilterIndex.cpp
es-app/src/guis/GuiGamelistOptions.cpp
es-app/src/guis/GuiGeneralScreensaverOptions.cpp
es-app/src/guis/GuiMenu.cpp
es-app/src/guis/GuiVideoScreensaverOptions.cpp
es-app/src/main.cpp
es-app/src/views/SystemView.cpp
es-app/src/views/ViewController.cpp
es-app/src/views/gamelist/BasicGameListView.cpp
es-app/src/views/gamelist/GridGameListView.cpp
es-app/src/views/gamelist/IGameListView.cpp
es-app/src/views/gamelist/ISimpleGameListView.cpp
es-core/src/Settings.cpp

Improving kids mode

---

es-app/src/scrapers/GamesDBScraper.cpp
es-core/src/HttpReq.cpp

Fix for scraper issue reported [here](https://retropie.org.uk/forum/topic/17925/emulationstation-scraping-thegamesdb-net-api-change)

set curl to follow redirects to fix scraper error

---

es-core/src/components/ImageComponent.cpp

Apologies @jrassa and all,
I missed some cases with rounding when the image was vertical.
This should fix things for good. My bad.

Final Fix for resizing images

---

es-core/src/resources/TextureData.cpp

Should fix #447 and #452, and should replace #453.
Thanks @hzulla for doing all the troubleshooting here.
Could you test and confirm it's eradicated? As it's not always reproducible, I fear that I may just have been lucky when testing.

Adjust mutex for SVG initialization and resizing

---

CMakeLists.txt
es-app/src/VolumeControl.cpp

As requested -> redirected from the original PR on stable.

Vero4k autodetection and volume mixer fix

---

es-app/src/components/TextListComponent.h
es-app/src/guis/GuiFastSelect.cpp
es-app/src/views/SystemView.cpp
es-app/src/views/UIModeController.cpp
es-app/src/views/gamelist/GridGameListView.cpp
es-app/src/views/gamelist/ISimpleGameListView.cpp
es-core/src/InputConfig.cpp
es-core/src/InputConfig.h
es-core/src/Window.cpp
es-core/src/components/ComponentGrid.cpp
es-core/src/components/ComponentList.cpp
es-core/src/components/DateTimeEditComponent.cpp
es-core/src/components/ImageGridComponent.h
es-core/src/components/OptionListComponent.h
es-core/src/components/SliderComponent.cpp
es-core/src/components/TextEditComponent.cpp

Browse in ES with all directionals, dpad and analogs. But it depends on https://github.com/RetroPie/RetroPie-Setup/pull/2529

Work with dpad and analogs

---

es-app/src/PlatformId.cpp
es-app/src/PlatformId.h
es-app/src/guis/GuiMetaDataEd.cpp
es-app/src/scrapers/GamesDBScraper.cpp

This should resolve [https://github.com/RetroPie/EmulationStation/issues/503](https://github.com/RetroPie/EmulationStation/issues/503) and [https://github.com/RetroPie/EmulationStation/issues/505](https://github.com/RetroPie/EmulationStation/issues/505).

Fixes for issues #503 and #505.

---

es-app/src/components/TextListComponent.h

Fix jagged font in games list

---

es-app/src/main.cpp
es-core/src/Renderer_init_sdlgl.cpp
es-core/src/Settings.cpp

Adds the ability to ask for a borderless fullscreen window.
Only tested on Windows 7 so far.

Add support for fullscreen borderless window

---

es-core/src/InputManager.cpp
es-core/src/InputManager.h

Reverts RetroPie/EmulationStation#449
Reverting for now as recommended by @psyke83 due to analogue stick configuration issues

Revert "InputManager: improve trigger axis calibration"

---

es-app/src/scrapers/ScreenScraper.cpp

> Started from https://github.com/RetroPie/EmulationStation/issues/565]
When the `platform` node has multiple entries, the scraper will do multiple requests for each _platformID_. If some of the platform entries map to the same platformID (i.e. like SEGA and MEGADRIVE) in ScreenScraper's module, this will produce duplicate requests and results.
The PR will remove the duplicate IDs, eliminating this bug.
To solve the problem from https://github.com/RetroPie/EmulationStation/issues/565, a separate PR would probably need to be made for https://github.com/RetroPie/RetroPie-Setup to adjust the `platforms.cfg` for the _megadrive_  system to include both platform names.

ScreenScraper: Eliminate duplicate requests for multiple platform entries

---

es-core/src/math/Transform4x4f.cpp

Fix Transform4x4f which was broken in many, many ways, but just out of pure luck worked anyway
Only tested on Windows but I see no reason why it shouldn't work on the Pi as well.

Fix Transform4x4f

---

es-core/src/renderers/Renderer_GLES10.cpp

Fixes compiling when Renderer_GLES10 is used

---

es-core/src/components/ImageComponent.cpp
es-core/src/components/VideoComponent.cpp
es-core/src/components/VideoComponent.h

applyTheme for ImageComponent and VideoComponent were duplicating code from GuiComponent

Image video component theme cleanup

---

es-app/src/components/RatingComponent.cpp
es-core/src/components/ImageComponent.cpp
es-core/src/components/NinePatchComponent.cpp

Spinning this off from #599.
Improved handling of opacity for ImageComponent

Opacity cleanup

---

es-app/src/FileData.cpp

Fix for [issue](https://github.com/RetroPie/EmulationStation/pull/592#issuecomment-527313763) caused by  #592.

ensure change flag cleared for new FileData

---

THEMES.md
es-app/src/CollectionSystemManager.cpp
es-app/src/views/gamelist/GridGameListView.cpp
es-app/src/views/gamelist/GridGameListView.h
es-core/src/ThemeData.cpp
es-core/src/ThemeData.h
es-core/src/components/GridTileComponent.cpp
es-core/src/components/GridTileComponent.h
es-core/src/components/ImageComponent.h
es-core/src/components/ImageGridComponent.h
es-core/src/utils/StringUtil.cpp
es-core/src/utils/StringUtil.h

Animate scrolling/selection, autoLayout option, center selection option, scroll loop option.

Grid updates

---

es-core/src/ThemeData.cpp
es-core/src/renderers/Renderer_GL21.cpp
es-core/src/renderers/Renderer_GLES10.cpp

Fixes for 2 issues reported on forums.
https://retropie.org.uk/forum/topic/9094/updated-emulationstation-for-windows/487
https://retropie.org.uk/forum/topic/23551/grid-updates-emulationstation-dev/21

add 'animate' to theme properties for imagegrid; fix blurriness on image upscaling

---

es-app/src/views/gamelist/GridGameListView.cpp

Need to repopulate list after applying theme to ensure image source is updated

Fix for GridView image source theme option

---

es-app/src/CollectionSystemManager.cpp
es-app/src/FileData.cpp
es-app/src/Gamelist.cpp
es-app/src/MetaData.cpp
es-app/src/MetaData.h
es-app/src/SystemData.cpp
es-app/src/SystemData.h
es-app/src/guis/GuiMenu.cpp
es-app/src/guis/GuiMetaDataEd.cpp
es-core/src/Settings.cpp
es-core/src/Settings.h

* made gamelist save option a multistate option with possible values "never", "always", "on exit" (default)

Added an option to save meta data instantly when changed.

---

es-app/src/components/TextListComponent.h

caused by the changes in #631.

input: fix the infinite scrolling with the left shoulder button

---

es-app/src/views/ViewController.cpp
es-app/src/views/gamelist/GridGameListView.cpp
es-app/src/views/gamelist/GridGameListView.h

Fix for metadata disappearing when selecting system for the first time.
Fix for video not resuming after launching game.

Grid View Fixes

---

es-core/src/Log.cpp

Timestamp'ed log entries

---

es-core/src/renderers/Renderer_GL21.cpp
es-core/src/renderers/Renderer_GLES10.cpp

Somehow the clearcolors were wrong and set to white, now fixed to be black

Fix clearcolors

---

CMakeLists.txt
es-core/CMakeLists.txt
es-core/src/renderers/Renderer_GL14.cpp

This should fix the issues some had with ancient stoneage GPU's

Add back OpenGl 1.4 renderer

---

es-app/src/CollectionSystemManager.cpp
es-app/src/views/SystemView.cpp

https://retropie.org.uk/forum/topic/26725/es-screensaver-ux-puzzles-and-suggestions

Some pluralization fixes. See proposed change no. 5 in

---

es-app/src/SystemScreenSaver.cpp
es-app/src/SystemScreenSaver.h
es-core/src/Window.cpp
es-core/src/Window.h

This is the third PR for the proposed change no. 4 of https://retropie.org.uk/forum/topic/26725/es-screensaver-ux-puzzles-and-suggestions
This first commit is the actual change the second commit are minor code style fixes.

Enables Launch and Next also in Slideshow Screensaver

---

es-app/src/FileSorts.h

Sorry, maybe it's not a bug, if someone with more knowledge can or wants to review it, I'm working on putting my personal emulatiostation in Spanish and I found this line by chance. 
IF this is not the proper way to report something please let me know, I don't control much github

es-app/src/FileSorts.cpp maybe a mistake

---

es-core/src/renderers/Renderer_GL14.cpp
es-core/src/renderers/Renderer_GL21.cpp
es-core/src/renderers/Renderer_GLES10.cpp
es-core/src/renderers/Renderer_GLES20.cpp

Eliminate unused variable glExts

Eliminate unused variable glExts

---

es-app/src/PlatformId.h
es-app/src/views/gamelist/GridGameListView.cpp
es-core/src/math/Misc.cpp
es-core/src/math/Transform4x4f.cpp
es-core/src/math/Vector2f.cpp
es-core/src/math/Vector3f.cpp
es-core/src/math/Vector4f.cpp
es-core/src/renderers/Renderer.cpp
es-core/src/renderers/Renderer_GL14.cpp
es-core/src/renderers/Renderer_GL21.cpp
es-core/src/renderers/Renderer_GLES10.cpp
es-core/src/renderers/Renderer_GLES20.cpp
es-core/src/utils/FileSystemUtil.cpp
es-core/src/utils/FileSystemUtil.h
es-core/src/utils/StringUtil.cpp
es-core/src/utils/TimeUtil.cpp

This is a big commit but it's 99% code style cleanups, a few variables changed into const.

Code style cleanups

---

es-app/src/CollectionSystemManager.cpp
es-app/src/guis/GuiCollectionSystemsOptions.cpp
es-core/src/math/Misc.cpp
es-core/src/math/Misc.h
es-core/src/math/Transform4x4f.cpp
es-core/src/math/Vector2f.cpp
es-core/src/math/Vector3f.cpp
es-core/src/math/Vector4f.cpp
es-core/src/renderers/Renderer.cpp
es-core/src/renderers/Renderer.h
es-core/src/renderers/Renderer_GL14.cpp
es-core/src/renderers/Renderer_GL21.cpp
es-core/src/renderers/Renderer_GLES10.cpp
es-core/src/renderers/Renderer_GLES20.cpp
es-core/src/utils/FileSystemUtil.cpp
es-core/src/utils/StringUtil.cpp
es-core/src/utils/StringUtil.h

Add Math::clamp<int>
Cleanup some code to properly use Math::round
Added const to a bunch of variables
Cleaned up a lot of functions in FileSystemUtil
removed StringUtil::commaStringToVector and vectorToCommaString, both can be done using delimitedStringToVector and vectorToDelimitedString

Lots of minor fixes and cleanups

---

es-core/src/resources/TextureDataManager.cpp

According to 6872f472 if MaxVRAM/--max-vram is 0, then texture memory should be considered unlimited
(command line help states - Max VRAM to use in Mb before swapping. 0 for unlimited)

Fix rendering when Max VRAM is set to 0

---

es-core/src/components/GridTileComponent.cpp
es-core/src/resources/TextureResource.cpp

And initialize TextureResource dimensions to 0 instead of garbage

Fix warning about ninepatch missing a texture.

---

es-app/src/views/gamelist/DetailedGameListView.cpp
es-app/src/views/gamelist/DetailedGameListView.h
es-app/src/views/gamelist/GridGameListView.cpp
es-app/src/views/gamelist/GridGameListView.h
es-app/src/views/gamelist/ISimpleGameListView.h
es-app/src/views/gamelist/VideoGameListView.cpp
es-app/src/views/gamelist/VideoGameListView.h
es-core/src/components/ScrollableContainer.cpp
es-core/src/components/ScrollableContainer.h

Had put the PR #695 in a FB in the meantime in my fork. Sorry for the inconvenience.
On the positive side: This PR only contains only the changes and no whitepace changes and is one commit/squashed.

Adds longer delay (5secs) for start of description text autoscroll.

---

es-app/src/CollectionSystemManager.cpp
es-app/src/CollectionSystemManager.h
es-app/src/SystemData.cpp
es-app/src/SystemData.h
es-app/src/main.cpp
es-app/src/views/ViewController.cpp
es-core/CMakeLists.txt
es-core/src/Settings.cpp
es-core/src/ThemeData.cpp
es-core/src/ThemeData.h
es-core/src/Window.cpp
es-core/src/Window.h
es-core/src/utils/FileSystemUtil.cpp
es-core/src/utils/ThreadPool.cpp
es-core/src/utils/ThreadPool.h

- Load systems using threaded loading when processor threads > 2 (so it doesn't apply on pi0), making loading systems faster.
- Added a progressbar during loading.
- Windows : added "sdl event dispatch" to avoid Windows thinking the app not responding during loading.

Added a progressbar during loading + threaded loading for systems

---

es-app/src/guis/GuiMenu.cpp
es-core/src/utils/StringUtil.cpp

IF reduce and Fix delete buffer

IF reduce and Fix delete buffer

---

es-core/src/components/ImageGridComponent.h

Now that we temporary save the textures, there is no need to update the grid from bottom to top when going up

Simplify grid tiles update code

---

es-app/src/views/gamelist/BasicGameListView.cpp
es-app/src/views/gamelist/BasicGameListView.h
es-app/src/views/gamelist/DetailedGameListView.cpp
es-app/src/views/gamelist/VideoGameListView.cpp
es-core/src/components/IList.h

fixes continued scrolling on system leave and reenter navigation

---

es-app/src/PlatformId.cpp
es-app/src/PlatformId.h
es-app/src/scrapers/GamesDBJSONScraper.cpp
es-app/src/scrapers/ScreenScraper.cpp

Added for scraping:
* TI-99 (ScreenScraper, TheGamesDB)
* Dragon32/64 (ScreenScraper)

scrapers: platform updates

---

es-app/src/views/gamelist/BasicGameListView.cpp

Remove thumbnail, video, image and marquee files for a game when the game file is removed.

gamelists: remove scraped files when removing game

---

CMake/Packages/FindVLC.cmake
es-app/src/CollectionSystemManager.cpp
es-app/src/FileFilterIndex.cpp
es-app/src/SystemData.cpp
es-app/src/SystemScreenSaver.cpp
es-app/src/components/RatingComponent.h
es-app/src/components/TextListComponent.h
es-app/src/guis/GuiGameScraper.h
es-app/src/guis/GuiInfoPopup.h
es-app/src/views/gamelist/BasicGameListView.h
es-app/src/views/gamelist/ISimpleGameListView.h
es-core/src/Log.h
es-core/src/Settings.cpp
es-core/src/animations/Animation.h
es-core/src/components/GridTileComponent.h
es-core/src/components/IList.h
es-core/src/components/ImageGridComponent.h
es-core/src/components/SwitchComponent.h
es-core/src/components/TextComponent.cpp
es-core/src/components/VideoComponent.h
es-core/src/components/VideoVlcComponent.cpp
es-core/src/components/VideoVlcComponent.h
es-core/src/guis/GuiTextEditPopup.h
es-core/src/platform.cpp
es-core/src/resources/Font.cpp
es-core/src/utils/StringUtil.cpp

A number of compilation errors and warnings addressed to allow building on Ubuntu 22.04.2 LTS (64-bit).
**Environment**
* clang (14.0.0-1ubuntu1.1) 14.0.0
* clang++ (14.0.0-1ubuntu1.1) 14.0.0
* cmake version 3.22.1
The original build log before modifications is attached for reference.
[build.log](https://github.com/RetroPie/EmulationStation/files/12130636/build.log)

Resolved compilation errors/warnings when building on Ubuntu 22.04.2 with clang

---

es-app/src/SystemScreenSaver.cpp

This is the minimal fix for the issue discovered in https://retropie.org.uk/forum/post/290190

Fixes 'blank screen effect' when custom video is used in slideshow

---

es-app/src/SystemScreenSaver.cpp
es-app/src/SystemScreenSaver.h
es-core/src/components/VideoVlcComponent.cpp
es-core/src/components/VideoVlcComponent.h

This is a refactoring/followup PR to #830
I guess this needs merge/squashing after #830 is applied.

Refactorings for "slideshow with custom video"  

---

es-app/src/SystemScreenSaver.cpp
es-app/src/guis/GuiGamelistOptions.cpp
es-core/src/components/VideoVlcComponent.cpp

Add new inputs support for image screensaver.

Update inputs for image screensaver

---

es-app/src/SystemScreenSaver.cpp
es-app/src/components/TextListComponent.h
es-app/src/guis/GuiGamelistOptions.cpp
es-app/src/views/ViewController.cpp
es-app/src/views/gamelist/BasicGameListView.cpp
es-app/src/views/gamelist/BasicGameListView.h
es-app/src/views/gamelist/GridGameListView.cpp
es-app/src/views/gamelist/GridGameListView.h
es-app/src/views/gamelist/IGameListView.h
es-app/src/views/gamelist/ISimpleGameListView.h

Hi @pjft as noted I have added a 
- constant variable for -1 (commit 0b408ca)
- did some refactorings and while being at it I discovered two cosmetic cornercases (commit 2537965)
- integrated your  remaining changes of #847 on top (commit 6f230a5)
With #850 (currently also in this PR as 9853840) I was not able to reproduce my issue nor the issue from user sleve in the forum.
Let me know any Qs and also if I should squash / reapply the PR once it is OK from your side.

Refactorings and two cornercases of 'screensaver enhanced controls'

---

es-app/src/CollectionSystemManager.cpp
es-app/src/guis/GuiCollectionSystemsOptions.cpp
es-app/src/guis/GuiRandomCollectionOptions.cpp
es-app/src/guis/GuiRandomCollectionOptions.h
es-core/src/Settings.cpp

- Updated labels
- Add "Exclusion" collection setting

Updates to Random Collections

---

es-app/src/CollectionSystemManager.cpp
es-app/src/CollectionSystemManager.h
es-app/src/guis/GuiCollectionSystemsOptions.cpp
es-app/src/guis/GuiRandomCollectionOptions.cpp
es-app/src/guis/GuiRandomCollectionOptions.h
es-core/src/Settings.cpp
es-core/src/Settings.h

As discussed. In short:
- Stick to C++11
- Support map storage for current feature (Random Collection) in Settings

Refactorings to #857 in C++11 standard

---

es-app/src/Gamelist.cpp

Fix for #861.
Prevent game launchers in a directory used as game launcher, as FileData::addChild() is only valid on filesystem folders with no or no valid game extension for that platform.
Example:
```
scummvm/Violet.svm/  # directory acts as game launcher in ES, bc. of the extension.
├── Violet.svm       # file is another valid game launcher.
└── Violet.zblorb
```
May be end up in the gamelist as:
```
...
<game>
<path>./Violet.svm</game> 
...
</game>
<game>
<path>./Violet.svm/Violet.svm</game> 
...
</game>
```

Fix for nested game launchers

---

es-app/src/CollectionSystemManager.cpp
es-app/src/components/TextListComponent.h
es-app/src/guis/GuiMenu.cpp
es-app/src/views/ViewController.cpp
es-app/src/views/ViewController.h

cf. https://retropie.org.uk/forum/topic/35365/

Fix cursor overrun in last played collection when LR/LB paging is used

---

external/nanosvg/nanosvg.h
external/nanosvg/nanosvgrast.h
external/nanosvg/src/nanosvg_impl.cpp

Updated with the latest nanosvg version, which includes mainly bugfixes and a few coloring SVG rendering improvements. Simplified a bit the cxx implementation source, since the all the necessary headers are included with `nanosvgrast.h`.

nanosvg: update from upstream
