RetroPie/EmulationStation

es-core/src/guis/GuiDetectDevice.cpp
Fix for problems like this:
http://blog.petrockblock.com/forums/topic/retropie-wont-recognize-ps3-controller-unless-ps-button-is-hit-before-es-start/
http://blog.petrockblock.com/forums/topic/elegent-method-of-detecting-wireless-controller-before-starting-es/
No controller found message pops up if no controller is connected. If a known controller is connected and any button is pressed system selection menu will show up instantly.
https://github.com/RetroPie/EmulationStation/issues/7
=> Skip controller config if known device is added after startup

es-app/CMakeLists.txt
Makes it installable on Debian Jessie (libboost 1.55.0)
=> Make libboost dependencies for Debian dependent on the found version

es-app/src/SystemData.cpp, es-app/src/SystemData.h, es-app/src/views/SystemView.cpp, es-app/src/views/ViewController.cpp, es-app/src/views/gamelist/BasicGameListView.cpp
Hi,
this idea came from friends I helped built RetroPie boxes.
For items like Kodi we found it helpful not to have to click twice when starting (once for the Ports meta system, and once for starting the port itself). Instead we wanted to add main menu items that launch items directly instead of showing a game list (this could also be useful for non-console emulators that only have one option in the game list currently).
The pull request adds the option to add a <directlaunch> tag to a system which will then allow this system to start it's command directly without showing the corresponding game list. If <directlaunch> is set to "true" only name and command are mandatory tags for this system. The system will show even if no path is set.
This might not be the cleanest solution to this, but I …
=> Add direct launch option for systems that don't need a game list

es-core/src/InputManager.cpp, es-core/src/guis/GuiDetectDevice.cpp, es-core/src/guis/GuiInputConfig.cpp
I ran into the issue where pageup/pagedown mappings don't work until you restart. This is because they're written to the initial config file as "leftbottom/rightbottom" and only changed to the required "pageup/pagedown" by the onfinish script.
It appeared to me that the code to write out a configuration file assumed onfinish would be executed afterward, because it wrote to a temporary location. So I think it makes sense to just go ahead and execute onfinish, and reload the resulting file for the current config right there, instead of relying on higher level code to remember to do it.
=> Fix pageup/pagedown by reloading input config after onfinish

external/nanosvg/nanosvg.h, external/nanosvg/nanosvgrast.h
I've created a branch where I've updated the SVG library used in EmulationStation (nanosvg).
First off, I want to make it absolutely clear that this is all @memononen's work. I did not do any work on this, I just merged in the latest version I found at https://github.com/memononen/nanosvg. I was unsure how to merge in this code using the normal git commands, as it is only a small part of the total ES repository, so I did it by hand. If there is a better way to do this (that keeps the commit history intact), let me know.
Using the reference image from http://www.scalablegfx.com/svg-test, and a butchered theme, I've created some comparison images.
Reference, before, and after images :
While it's not perfect yet, I think the benefits of this update are clear to see. This should solve the …
=> SVG renderer update

es-core/src/Window.cpp
Running ES in Udon Quad (i.MX6) crashes with the following bt
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x76c5b08c in glGenTextures () from /usr/lib/arm-linux-gnueabihf/libGL.so.1
(gdb) bt
#0  0x76c5b08c in glGenTextures () from /usr/lib/arm-linux-gnueabihf/libGL.so.1
#1  0x00104f60 in TextureResource::initFromPixels(unsigned char const*, unsigned int, unsigned int) ()
#2  0x0010503a in TextureResource::initFromMemory(char const*, unsigned int) ()
#3  0x00105466 in TextureResource::reload(std::shared_ptr<ResourceManager>&) ()
#4  0x00105ada in TextureResource::get(std::string const&, bool) ()
#5  0x000ed686 in ImageComponent::setImage(std::string, bool) ()
#6  0x000dbc4c in Window::Window() ()
#7  0x0005a800 in main ()
```
The problem seems to be that libGL …
=> Fixes libGL problem

es-core/src/InputManager.cpp, es-core/src/InputManager.h
Unlike other axis, they don't default to 0, but instead start at -32768 and go to +32767 when pressed. This confuses the
current ES code axis code. As a workaround, we get the initial value and if it is -32767, we add 32767 and divide by two. This gives it
a range that can be handled with the current code (from 0 to 32767). Note on my X11 machine, I had to plug the joystick in after ES
was loaded or it get 0 as the initial axis value for the triggers. This seems ok on the RPI though, so possible some SDL issue.
With this change on a 360 controller the triggers should be correctly detected as +2 and +5 without seeing two presses for each trigger press.
=> workaround for analogue trigger configuration - eg with xpad.

.gitignore, es-app/src/FileData.cpp, es-app/src/FileData.h, es-app/src/Gamelist.cpp, es-app/src/SystemData.cpp, es-core/src/Util.cpp, es-core/src/Util.h
Included in this pull request are two changes that vastly improve the loading time of EmulationStation for users who have a large amount of games.
1. The `ParseGamelistOnly` option no longer checks files exist in the filesystem
2. The `FileData` class uses a `vector` to store files but also tries to insert elements into the vector if and only if they do not already exist. This is O(n). I have added an `unordered_map` to track elements and so the algorithm is now O(1).
On my Pi with about 20,000 games, this reduced loading time from over 30 minutes to roughly a minute or so.
=> Vastly improve loading time of EmulationStation

es-app/src/Gamelist.cpp, es-app/src/MetaData.cpp, es-app/src/MetaData.h
The cause for long save times for those with large libraries is caused by the games that don't have metadata.  Before it appends the new game's metadata node to the tree it first finds the old one and deletes it using a for loop.  The problem is that a game that has no metadata also will not be in the gamelist.xml file so it will loop through the whole tree until it hits the last node.
This fix adds a function to metadata that will return true if all metadata is still set at its defaults.  This is then used to just skip that game and not try looking for it in the gamelist.
I threw together a [spreadsheet](https://docs.google.com/spreadsheets/d/1k4rUefg8XoclnI8LD-8hj6-LqY1_LfYyok3ZkHsNQos/edit?usp=sharing) that shows the difference in performance.  These results are from retropie.org.uk …
=> Fix for long exit times while saving metadata

es-core/src/components/IList.h
@HerbFargus et al I'm looking for some feedback on this if possible. I find on my system when scrolling ES scrolls quite slowly, but then jumps to a silly speed, meaning you often go past the entry you are looking for in a large list.
I slowed down the fastest scroll speed, and added an additional tier. I also adjusted the timings (2 seconds for first speed increase, then 4 seconds for next).
=> emulationstation - add additional scroll speed tier, and slow down fastest speed

CMake/Packages/FindVLC.cmake, CMake/Packages/MacroEnsureVersion.cmake, CMakeLists.txt, README.md, es-app/CMakeLists.txt, es-app/src/FileData.cpp, es-app/src/FileData.h, es-app/src/MetaData.cpp, es-app/src/MetaData.h, es-app/src/views/ViewController.cpp, es-app/src/views/gamelist/VideoGameListView.cpp, es-app/src/views/gamelist/VideoGameListView.h, es-core/CMakeLists.txt, es-core/src/GuiComponent.cpp, es-core/src/GuiComponent.h, es-core/src/ThemeData.cpp, es-core/src/ThemeData.h, es-core/src/Window.cpp, es-core/src/components/VideoComponent.cpp, es-core/src/components/VideoComponent.h
This feature has been discussed in https://retropie.org.uk/forum/topic/4820/video-preview-in-emulationstation and a request for testing has been submitted in https://retropie.org.uk/forum/topic/5823/looking-for-testers-for-es-video-preview-on-raspberry-pi. Please refer to these threads for details on the implementation, theming and testing.
=> Add video view to allow video preview of games in gamelist

es-app/src/Gamelist.cpp, es-app/src/MetaData.cpp, es-app/src/MetaData.h
This is a proposal to speedup the shutdown of ES and actually make it shutdown instantly. Usually, ES writes back metadata of all files from all systems to the gamelist.xml. With this PR, ES will keep track of changes to the metadata at runtime and only write back changed entities upon shutdown.
When shutting down there will be a summary of changed gamelist.xmls:
```
lvl1: 	OptionListComponent too narrow!
lvl2: 	Added/Updated 0 entities in '/home/vbs/.emulationstation/gamelists/3do/gamelist.xml'
lvl2: 	Added/Updated 0 entities in '/home/vbs/.emulationstation/gamelists/amiga/gamelist.xml'
lvl2: 	Added/Updated 1 entities in '/home/vbs/.emulationstation/gamelists/atari7800/gamelist.xml'
lvl2: 	Added/Updated 0 entities in '/home/vbs/.emulationstation/gamelists/atarijaguar/gamelist.xml'
lvl2: …
```
=> Instant Shutdown by only writing changes to gamelist.xml

es-app/src/views/ViewController.cpp, es-core/src/ThemeData.cpp, es-core/src/ThemeData.h
Provides improved compatibility for video view with older themes.  Currently, if using a theme that does not support video, user will get the default white screen theme if they have videos in their gamelist.xml.  This change checks if the active theme supports video and if not it will use the detailed view vs. video.
=> don't enable video view if current theme doesn't support it

es-core/src/ThemeData.cpp, es-core/src/components/VideoComponent.cpp, es-core/src/components/VideoComponent.h
This change will bring videos inline with how images work by supported maxSize.  When using maxSize, the video will still maintain its aspect ratio.
=> implement maxSize for videos

.gitignore, CMakeLists.txt, THEMES.md, es-app/src/views/SystemView.cpp, es-app/src/views/SystemView.h, es-app/src/views/ViewController.cpp, es-core/src/ThemeData.cpp, es-core/src/Util.cpp, es-core/src/components/TextComponent.cpp, es-core/src/components/TextComponent.h, es-core/src/platform.cpp
Hello dear RetroPie Core team!
I would like to offer some changes that allow the theming of the system carousel element, as shown in the system view of EmulationStation. This was developed together with @jrassa, who was a great help in finetuning the default behaviour, and ironing out some of the bugs.
This feature has been tested and all discovered bugs have been crushed, see the forum thread [here ](https://retropie.org.uk/forum/topic/2696/input-needed-es-theming-improvements/145).
As the development took a while, and was parallel to other developments on this stream, there were a couple of rebases I wanted to have in, in order to do better testing. As a result, there were many more commits than only mine on the branch, which were very tiresome to disentangle. So while I intended to …
=> System carousel theming

es-app/src/views/gamelist/VideoGameListView.cpp, es-app/src/views/gamelist/VideoGameListView.h
Issue reported here.
https://retropie.org.uk/forum/topic/9261/bug-box-art-displaying-incorrect-size-the-first-time-i-enter-a-system/
=> fix image ratio for first image in video game list view

es-app/src/views/SystemView.cpp
Currently, carousel theming is loaded from first system theme.  If current theme does not support the first system then the carousel theming will not be applied.  This change adds a simple check to see if the current system theme supports system view, if it does not, it try to load the carousel theming from the next system theme.
=> Fix for carousel theming

es-app/src/FileData.cpp, es-app/src/MetaData.cpp, es-app/src/guis/GuiGamelistOptions.cpp, es-app/src/views/gamelist/DetailedGameListView.cpp, es-app/src/views/gamelist/VideoGameListView.cpp
Hi. It's my second attempt at my first PR. I believe I squashed the commits.
I have no idea why the commit is signed by two authors with my username.
For people who use subfolders in their gamelist, we currently provided a sub-optimal experience:
Allowed to show images, but not videos;
Allowed for editing, but the GUI would show up incomplete;
Did not show some of the metadata, if it existed on the gamelist (i.e. number of players, stars, etc), especially useful for multi-disc games under the same folder, or even for category groupings.
This small change enables video playback for folders, when selected, and also opens up a lot more of the metadata to the folders (in fact, all but the "Last Played" date, and "Play Count").
Hope it suits.
Thanks.
=> Adding metadata to folders

es-app/src/guis/GuiGamelistOptions.cpp, es-app/src/main.cpp, es-app/src/views/SystemView.cpp, es-app/src/views/ViewController.cpp, es-app/src/views/ViewController.h, es-app/src/views/gamelist/BasicGameListView.cpp, es-app/src/views/gamelist/ISimpleGameListView.cpp
Hi!
This is a PR to enable users to jump to a random game with the push of a button (currently: x). The idea is to get people to play games they would otherwise not consider playing, especially when they have a large collections of games to choose from.
The changes are relatively small, and tested on a test-collection with sub-folders.
I am unsure if recounting all the games every time this is called will take prohibitively long or not, so I would like to get some feedback on that, if possible. I've tried it with a setup with 20K (dummy) files for a system, and that had no discernable effect on performance. Note that this was on a windows machine, but I suspect it will not matter, as ES gets the info from it's internal data-structures (in RAM) anyways.
Let me know what you think!
=> Go-to Random Game feature

es-app/src/guis/GuiMenu.cpp, es-app/src/views/ViewController.cpp, es-app/src/views/ViewController.h, es-core/src/Settings.cpp
Currently supports Basic, Detailed, Video, and Automatic types. The Automatic type checks for the availability of video's first, then screenshots, finally defaulting to Basic view if none are present.
=> Add Explicit Gamelist Type selection to GUI menu.

es-app/src/views/SystemView.cpp, es-core/src/AudioManager.cpp, es-core/src/Renderer_init_sdlgl.cpp, es-core/src/components/IList.h
Hi. I'm proposing to add two options that will help improve the perceived performance in heavier themes.
- Option to not use multithreaded image loading, like old ES (default: use multithread, like today)
- Option to re-use SVG in-memory images in same path (default: not re-use, like today)
In the recent WSOD changes, one improvement was to load images in separate threads. While this works well for non-heavy themes, it causes an unpleasant white screen to show before the actual images are rendered, when they need to be cycled in the texture manager memory. Forcing them to be loaded like the old ES, in the same thread, will cause a potentially less smooth system view scrolling, at the exchange of no more white screens.
Also, SVGs from the same path are not re-used throughout the theme, but …
=> Changes to mitigate white flashes in heavier themes

.gitmodules, es-app/src/guis/GuiMenu.cpp, es-app/src/views/gamelist/VideoGameListView.cpp, es-app/src/views/gamelist/VideoGameListView.h, es-core/CMakeLists.txt, es-core/src/GuiComponent.cpp, es-core/src/GuiComponent.h, es-core/src/Settings.cpp, es-core/src/Window.cpp, es-core/src/Window.h, es-core/src/components/VideoComponent.cpp, es-core/src/components/VideoComponent.h, es-core/src/components/VideoPlayerComponent.cpp, es-core/src/components/VideoPlayerComponent.h, es-core/src/components/VideoVlcComponent.cpp, es-core/src/components/VideoVlcComponent.h
---- Changes summary ----
- Added OMX Player as an option to ES (Only available on the RPi. Default: disabled)
- Generalized "VideoComponent" class, and created two child classes - one for VLC, one for OMX. In the future it's easy to just remove the OMX one, and/or create a new one for another video renderer we choose to use (ffmpeg? Something else?), so these are easy to revert. The bulk of this work was done by @fieldofcows - he is the git author of that commit in this PR, I just squashed it, and added my fixes and changes separately.
- Added option to mute videos. 
---------------------------
OMX Player has better performance on the Pi than VLC. @fieldofcows did a great work adding it to a separate branch, earlier in the year.
Since then, I ended up picking it up and improving it …
=> Adding OMX Player as experimental option for ES

es-app/src/components/ScraperSearchComponent.cpp, es-app/src/scrapers/Scraper.cpp
The changes in scrapper.cpp make it non-blocking and the 'mBlockAccept = true;' makes ScraperSearchComponent::render and ::update use and show mBusyAnim.
Maybe there's a better way to show the BusyComponent but it works for me.
=> Make Scraper non-blocking

es-app/src/views/SystemView.cpp, es-app/src/views/gamelist/IGameListView.cpp, es-app/src/views/gamelist/IGameListView.h
Fix for issues with view elements overflowing into "adjacent" views.
https://retropie.org.uk/forum/topic/10635/theme-backgrounds-getting-cut-1-4
https://retropie.org.uk/forum/topic/9785/z-index-support-for-themes/27
=> use clip rects to prevent views overflow onto other views

es-app/src/VolumeControl.cpp, es-app/src/guis/GuiMenu.cpp, es-core/src/Settings.cpp, es-core/src/components/VideoPlayerComponent.cpp
- Ability to change device used for Volume control (PCM/Speaker/Master) only on Pi.
- Ability to change Audio device used for OMX player (local/hdmi/both/ALSA:HW:0,0/ALSA:HW:1,0)
=> Fixes for USB sound cards

es-app/CMakeLists.txt, es-app/src/SystemScreenSaver.cpp, es-app/src/SystemScreenSaver.h, es-app/src/guis/GuiMenu.cpp, es-app/src/guis/GuiMenu.h, es-app/src/guis/GuiScreensaverOptions.cpp, es-app/src/guis/GuiScreensaverOptions.h, es-app/src/main.cpp, es-app/src/views/SystemView.cpp, es-app/src/views/gamelist/BasicGameListView.h, es-app/src/views/gamelist/DetailedGameListView.h, es-app/src/views/gamelist/GridGameListView.h, es-app/src/views/gamelist/IGameListView.h, es-app/src/views/gamelist/ISimpleGameListView.h, es-app/src/views/gamelist/VideoGameListView.cpp, es-app/src/views/gamelist/VideoGameListView.h, es-core/src/GuiComponent.h, es-core/src/Settings.cpp, es-core/src/Window.cpp, es-core/src/Window.h, es-core/src/components/VideoComponent.cpp, es-core/src/components/VideoComponent.h, es-core/src/components/VideoPlayerComponent.cpp, es-core/src/components/VideoPlayerComponent.h, es-core/src/components/VideoVlcComponent.cpp, es-core/src/components/VideoVlcComponent.h, es-core/src/platform.h
- Adding random video screensaver option (by @fieldofcows, I just squashed the commits). Videos change after 35s. ES will try to load a random video that the gamelist references, and will retry up to 200 times (i.e. 200 consecutive random videos) in case it can't find a particular video file. If after 200 tries none of the random paths from the gamelist pointed to any valid file, it will default to the black screensaver.
- Added option to control the random video screensaver: if enabled, you can launch the game that's being shown at the time (press start or X during the screensaver), skip to another video before the 35s are elapsed by pushing "right" on your joystick, and launch the screensaver by pressing "Select" on the system view. If disabled, it works as normal.
- You can also choose …
=> Adding Random Video Screensaver/Attract Mode, plus controls

es-app/src/components/TextListComponent.h
When I originally implemented these changes, for the themes that I focused on, the computed size of the font was slightly smaller than the size specified in the theme.  Unexpectedly, for some themes the opposite was true, and in some cases the difference was pretty big.  This caused the issues reported in #164.  The fix is pretty simple, it is just comparing the two sizes and using the larger value.
=> fix gamelist sizing by using max of computed size vs set size

es-app/src/guis/GuiGamelistOptions.cpp
used/useful feature.
Also, this is where it previously was:
I have seen someone else bothered by how it was changed the forum but can't find the post now :(
=> Returned 'JUMP TO LETTER' option back to top of menu, as it is the most

THEMES.md, es-app/src/SystemData.cpp, es-app/src/views/SystemView.cpp, es-core/src/ThemeData.cpp, es-core/src/ThemeData.h
Themes can define variables that can then be referenced later in the the theme.  There are also a few predefined variables that are populated based on values in es_systems.cfg.
Example:
```
<variables>
<themeColor>8b0000</themeColor>
</variables>
<color>${themeColor}c0</color>
<path>./art/logo/${system.theme}.svg</path>
```
Themes can also provide a default theme that will be used when there isn't a matching system theme.  Default theme must be named theme.xml and be found in root of theme directory.
In addition, logoText (used on system view when a logo is unavailable) can now be themed.
Use of variables is optional and existing themes should continue to work as before.
Here is an example of how theme creation can be simplified with this feature.  I modified carbon to use variables. …
=> variable support for themes

es-app/src/guis/GuiMenu.cpp
As some controllers have trouble navigating the menus when sliders are not on top.
The component hasn’t been changed since Aloshi’s time, so this probably has been around since ever.
Alas, I cannot reproduce it with my controller, so this is the best I can do for the time being.
Addresses #176 .
=> Moving slider entries in the menus back to the top

es-app/src/SystemData.cpp, es-app/src/guis/GuiGamelistOptions.cpp, es-app/src/guis/GuiMenu.cpp
- Fixing off-by-one error when selecting games from list
- Update system exclusion list for random selection
- Removed "Surprise Me!" option from menu
- Update menu alignment
---
Sorry about that. A small quick fix from the random selection refactoring. It was crashing with a off-by-one error when the random number ended up being larger than the list size.
=> Fixing random game selection, and aligning menus

es-app/src/components/TextListComponent.h, es-app/src/guis/GuiGameScraper.cpp, es-app/src/guis/GuiMenu.cpp, es-app/src/guis/GuiScraperMulti.cpp, es-app/src/main.cpp, es-app/src/views/SystemView.cpp, es-app/src/views/ViewController.cpp, es-core/CMakeLists.txt, es-core/src/PowerSaver.cpp, es-core/src/PowerSaver.h, es-core/src/Settings.cpp, es-core/src/components/ScrollableContainer.cpp, es-core/src/components/VideoVlcComponent.cpp
Major changes:
- Change Power Saver (PS) from Other Settings menu
- 4 Modes are available : Disabled, Default [default], Enhanced, Instant
- Disabled : PS is disabled and redundant frames are rendered constantly
- Default : PS is triggered after Description has scrolled once
- Enhanced : PS is triggered after Game Name scrolls once. Use when you don't need/read Description. 
- Instant : Goes well with Instant Transition Style and Carousel transition disabled.
- All modes work well with Screensavers and Video previews.
- PS is disabled while running Videos through VLC.
- PS is disabled while Scrapping 
- Game counts are shown immediately if in Instant Mode
- PS mode defaults if Transitions are changed while in Instant Mode
Saves 40-45% CPU consumption on single core Pi 1/0/0w and 10% on …
=> Implement Power Savings feature

es-app/src/SystemData.cpp, es-app/src/guis/GuiMenu.cpp, es-app/src/main.cpp, es-core/src/Settings.cpp
Re-do of  #182 - turns out adding options was pretty easy to do blind :)
- Has option in 'OTHER SETTINGS' - 'SHOW HIDDEN FILES' - defaults to false
- Re-wrote function myself.
- Removed folder check - existing ES didn't seem to show hidden directories anyway, so it would never go into my function.
- Requires ES restart to take effect.
Will do one final test tonight.
=> Skip hidden *nix files when populating gamelists.

es-core/src/resources/Font.h
Adjusts default font sizes when ES is running in vertical orientation.  Previously the font sizes were based on the screen height.  When running in vertical orientation, the screen height is larger, which results in larger default fonts.  This can cause rendering issues for the menus.
=> fix default font sizes when running in vertical orientation

es-app/src/main.cpp, es-core/src/Log.cpp, es-core/src/Log.h
Small change to always keeps one session’s log backup file. It's hard to request logs from our users as restarting ES/RetroPie will always erase the previous session's log file.
=> Backup previous session's Log file

es-app/src/SystemScreenSaver.cpp, es-app/src/SystemScreenSaver.h, es-app/src/guis/GuiMenu.cpp, es-app/src/main.cpp, es-core/src/PowerSaver.cpp, es-core/src/PowerSaver.h
- Removed warning while enabling Instant mode
- Fixes #198  Instant mode setting not being saved
- Fixes #200 Fast animations when Screensaver is disabled by setting timeout to 0
- Added methods to support changing screensaver videos after timeout
while using OMX.
- Added methods to support changing Screensaver play next video timeout
- Minor fixes
=> PowerSaver Updates

THEMES.md, es-app/src/guis/GuiFastSelect.cpp, es-app/src/guis/GuiMenu.cpp, es-app/src/views/SystemView.cpp, es-app/src/views/SystemView.h, es-app/src/views/ViewController.cpp, es-app/src/views/gamelist/ISimpleGameListView.cpp, es-core/src/GuiComponent.cpp, es-core/src/ThemeData.cpp, es-core/src/components/MenuComponent.cpp, es-core/src/components/OptionListComponent.h, es-core/src/components/TextComponent.cpp, es-core/src/components/TextComponent.h, es-core/src/resources/Font.h
* The scaling of the logos will now animate properly and they will grow and shrink gradually as they become selected/unselected. This has added benefit of simplifying some of the code. Previously, we created 2 images for each logo, a normal and a selected image. With this change we are now only creating one.
* Opacity change of logos is also animated properly.
* Text logos now increase is size properly. This should reduce/eliminated the `...` that are seen sometimes now with carbon when using the new game collections feature.
* Origin supported for setting carousel position.
* Fixed a bug where background extras would bleed into gamelists when using vertical carousel.
* Alignment options for the logos.
* New vertical wheel carousel type.
=> carousel enhancements

es-core/src/components/VideoPlayerComponent.cpp
Changed the OMX Player logic to respect the sound settings slider.
Thanks to @hex007 for taking a stab at it, and thanks @jrassa for the [handy documentation](https://stackoverflow.com/a/40967467) on explaining the OMXPlayer volume formula (I would have guessed it'd be linear, rather than logarithmic).
This should address #187 .
Thanks.
=> Making OMXPlayer respect sound settings

es-app/src/views/SystemView.cpp
Fix for carousel when only 1 system exists.  Now properly only shows 1 logo and disables scrolling.
=> properly render carousel for system configured with only 1 system

es-app/src/views/gamelist/BasicGameListView.cpp
Sorry for that. This should revert the changes that are causing a pointer failure on Font.cpp in Ubuntu.
=> Revert Help Text getting string pointer

es-core/src/Settings.cpp
More often than not users are running into glGetErrors 505 (running out of video memory) when using heavy themes with the default 100 VRAM setting.
The advice of setting it to 80 is often the solution.
Until we have a proper/better GPU management solution, this is probably a better default.
**Disclaimer: I have not compiled this (lacking hardware access at the moment).**
=> Setting VRAM default at 80 for the Pi

es-app/src/CollectionSystemManager.h, es-app/src/views/gamelist/BasicGameListView.cpp, es-core/src/GuiComponent.h, es-core/src/Window.cpp, es-core/src/components/ComponentGrid.cpp, es-core/src/components/ComponentList.cpp, es-core/src/components/HelpComponent.cpp
I've built EmulationStation on Ubuntu 17.04 and it always triggers an assert() because of invalid utf-8 codepoints when I open a game system view.
After some debugging I saw that it uses a char pointer from a temporary std::string object, and when that pointer reaches the assert() the string was already overwritten by something else.
I would guess that this issue might not occur with older GCC versions or with the old C++ ABI settings because the old ref-counted std::string would have meant that the string would not have been deleted with the temporary object.
=> fix delete-after-use issue with temporary string

es-app/CMakeLists.txt, es-app/src/SystemScreenSaver.cpp, es-app/src/SystemScreenSaver.h, es-app/src/guis/GuiGeneralScreensaverOptions.cpp, es-app/src/guis/GuiGeneralScreensaverOptions.h, es-app/src/guis/GuiMenu.cpp, es-app/src/guis/GuiScreensaverOptions.cpp, es-app/src/guis/GuiScreensaverOptions.h, es-app/src/guis/GuiSlideshowScreensaverOptions.cpp, es-app/src/guis/GuiSlideshowScreensaverOptions.h, es-app/src/guis/GuiVideoScreensaverOptions.cpp, es-app/src/guis/GuiVideoScreensaverOptions.h, es-core/src/PowerSaver.cpp, es-core/src/Settings.cpp
This change adds an image slideshow screensaver mode with optional
background audio.  The existing menu and video screensaver have been
refactored to include this new mode.
By default, the slideshow screensaver will show images from the
game list, but it can be configured in the menu to use a custom
directory instead.
=> Add image slideshow screensaver mode

CMake/Packages/FindOpenGLES.cmake, CMakeLists.txt
* For BCMHOST build, use brcmEGL / brcmGLESv2 libraries, and don't look at
Mesa includes (so libraspberrypi-dev and libgles*-mesa-dev can coexist).
* If overridden via -DGLES=On, don't present vendor includes to build to
make absolutely sure that the Mesa includes are used.
Fixes stretch vendor library building & generic Mesa GLES compatibility.
=> CMake: use correct Raspberry Pi library names & fix generic GLES support

es-core/src/components/VideoPlayerComponent.cpp
This commit aims to make the OMX Player volume as close to the ALSA/VLC one as possible, as the ES Sound Settings slider goes lower. The previous formula, found online, didn't seem to match what was intended, so after experimenting with the several levels and what sounded similar, this is a better approximation.
=> Second stab at normalizing volume scale for OMX Player

es-app/src/components/ScraperSearchComponent.cpp, es-app/src/scrapers/GamesDBScraper.cpp, es-app/src/scrapers/GamesDBScraper.h, es-app/src/scrapers/Scraper.cpp
I noticed that the scrapper is sometimes very strict in how the game has to be named in order to find it. After some analysis I saw that it's using the GetGame.php API call, but GetGamesList.php is the one that is meant to be used for searching.
There is one caveat with GetGamesList: Apparently their search heuristics filter out numbers or something. I found this out when trying to scrape the game "1942", which it doesn't find. The regular search feature on thegamesdb.net also doesn't find it, even though it's definitely in the database. I consider this a bug in their search feature. Interestingly, GetGame.php does find it. I guess I could add a fallback to GetGame.php if no games are found, if you think it's necessary.
I also changed the limit on the number of results. Previously it was …
=> TheGamesDB scrapper should use GetGameList.php

es-app/src/FileFilterIndex.cpp, es-app/src/MetaData.cpp, es-app/src/SystemData.cpp, es-app/src/SystemScreenSaver.cpp, es-app/src/guis/GuiInfoPopup.cpp, es-app/src/guis/GuiMetaDataEd.cpp, es-app/src/main.cpp, es-app/src/views/SystemView.cpp, es-app/src/views/ViewController.cpp, es-app/src/views/ViewController.h, es-app/src/views/gamelist/BasicGameListView.cpp, es-app/src/views/gamelist/VideoGameListView.cpp, es-core/src/GuiComponent.cpp, es-core/src/GuiComponent.h, es-core/src/components/ImageComponent.cpp, es-core/src/components/MenuComponent.cpp, es-core/src/components/TextEditComponent.h, es-core/src/components/VideoComponent.cpp, es-core/src/components/VideoVlcComponent.cpp, es-core/src/resources/TextureData.cpp
This is a cleanup pr, fixing some build warnings that pop up during compilation in VS2015.
These concern mostly adding explicit type casting that have no functional difference.
I've also removed a method in ViewController.cpp that was no longer used (goToRandomGame() RIP), and removed some unused variables.
=> Fix build warnings (mostly adding explicit type casting)

es-core/src/Renderer_init_sdlgl.cpp, es-core/src/Settings.cpp
* Now that vsync off explicitly sets swap interval, it's clear that
we've been using driver defaults (vsync on) up until now.
* Try to enable normal vsync before late swap tearing. The latter
doesn't constrain framerate and looks basically identical to vsync
off.
=> Pi: use vsync by default and fix vsync on case

es-app/src/FileData.cpp, es-app/src/components/TextListComponent.h, es-app/src/guis/GuiMenu.cpp, es-core/src/AudioManager.cpp, es-core/src/PowerSaver.cpp, es-core/src/Sound.cpp, es-core/src/components/VideoPlayerComponent.cpp
I figured out the issue with constant 2-3% CPU usage. When the audio driver is opened via SDL_OpenAudio, there will be a constant stream of failing ioctls from the ALSA driver, even when there's no active playback.
**strace -f -p $(pidof emulationstation)** will show this spammed constantly, even during idle & no background audio running: 
```
4326  ioctl(4, SNDRV_PCM_IOCTL_WRITEI_FRAMES, 0x76f2edc0) = -1 EAGAIN (Resource temporarily unavailable)
4326  ioctl(4, SNDRV_PCM_IOCTL_WRITEI_FRAMES, 0x76f2edc0) = -1 EAGAIN (Resource temporarily unavailable)
4326  ioctl(4, SNDRV_PCM_IOCTL_WRITEI_FRAMES, 0x76f2edc0) = -1 EAGAIN (Resource temporarily unavailable)
4326  ioctl(4, SNDRV_PCM_IOCTL_WRITEI_FRAMES, 0x76f2edc0) = -1 EAGAIN (Resource temporarily unavailable)
4326  ioctl(4, …
```
=> Power Saving enhancements

es-core/src/components/VideoComponent.cpp
I think this should have gotten rid of the warnings, after reading up on what caused them in the first place.
Apologies if that's not he case, as I can't reproduce the warnings on the default Pi compiler.
=> Video String Formatting Warning Fixes

es-app/src/FileFilterIndex.cpp, es-app/src/FileFilterIndex.h, es-app/src/MetaData.cpp, es-app/src/SystemData.cpp, es-app/src/SystemData.h, es-app/src/guis/GuiGamelistFilter.cpp, es-app/src/guis/GuiMenu.cpp, es-app/src/main.cpp, es-app/src/views/SystemView.cpp, es-app/src/views/ViewController.cpp, es-app/src/views/ViewController.h, es-app/src/views/gamelist/BasicGameListView.cpp, es-app/src/views/gamelist/ISimpleGameListView.cpp, es-core/src/Settings.cpp
This is the second part of the UI modes delivery.
It build on part one (shielding ES menus), by employing the filter mechanism in order to hide items that are unwanted.
Two modi operandi are introduced here:
1. Kiosk, where only specific items are hidden, and all else is shown.
2. Kid, where only specific items are shown, and all else is hidden.
This filtering is based on two new metadata values for these items `hidden` and `kidgame`, both of type boolean.
This brings the total number of UI modes to three: Full, Kiosk and Kid.
Final cleanup of automatic whitespace shifts and such will be done once everyone has had a chance to have a look at this.
=> UI modes part 2: Kid mode (File Filtering and system hiding)

es-app/src/scrapers/GamesDBScraper.cpp, es-app/src/scrapers/Scraper.cpp, es-core/src/Settings.cpp, es-core/src/ThemeData.cpp, es-core/src/components/HelpComponent.cpp
Eliminated one more dependency on boost, this time, boost::assign::list_of
This also eliminated the need for some template hack in ThemeData someone added due to boost misbehaving on gcc.
=> Removed all boost::assign::list_of

es-app/src/Gamelist.cpp, es-app/src/SystemData.cpp, es-app/src/SystemData.h
Add SystemData::indexAllGameFilters that loops through all added games and add's their tags to the filter indexes
This fixes the hidden filtering in Kiosk mode when not using gamelist.xml
This fixes https://github.com/RetroPie/EmulationStation/issues/281
=> Add SystemData::indexAllGameFilters (fixes bug #281)

es-app/src/SystemScreenSaver.cpp
This fixes #245 .
Tested with VLC, OMX Player, and different combinations on the Pi. All seems good.
=> Fix for Video Screensaver not showing if menu is open

es-app/src/components/TextListComponent.h, es-core/src/GuiComponent.h, es-core/src/math/Misc.h
I added math/Misc.h that defines ES_PI, ES_RAD_TO_DEG and ES_DEG_TO_RAD
Also added Math::bounce that takes a delay time, a bounce time and your current time
This is what it does:
```
// returns a float between 0.0 and 1.0
// delay, 0.0 -> 1.0, delay, 1.0 -> 0.0
```
Basically if given time is less than first delay, it does nothing and returns 0, then it goes up to 1 for the duration of bounce, delays again and returns 1 until its time to go back down to 0 for the duration of bounce, delays again and returns 0,
So a negative time or larger than delay + bounce + delay + bounce also returns 0
It's up to the code outside to handle feeding it a proper time.
I applied this to the long romname scroll so it doesn't just stops and sit at the end of a long name, but bounce back and forth.
Oh, also, …
=> Make long romnames bounce back and forth

es-app/src/CollectionSystemManager.cpp
Should fix #289.
Edge case for file deletion when the file is present inside a collection that is itself inside the "My Collections" bundle. We were updating the System View for the collection (which is not being used in this case), instead of updating the Gamelist View for "My Collections" (the one that is being used in this case).
Segmentation fault ensues.
=> Fixing file deletion when present in "My Collections" bundle

es-app/src/main.cpp
This should fix the crash introduced by https://github.com/RetroPie/EmulationStation/commit/d3966da2b7ed13f39b2b90e6ba008c4dfdb84de6
Tested on Windows 7, Ubuntu 16.04 and on my pi3. Most themes tested shows just dots or squares, but I blame that on the font, and as far as I can tell it did this even when it was using boost::locale.
=> Trying to fix japanese text

es-app/src/guis/GuiMenu.cpp
To counter [this issue](https://retropie.org.uk/forum/topic/14294/main-menu-troubles), and one other such confusion earlier this week.
Users will now see this:
Limitations: 
1. The current message string is hard-coded, meaning that if people change their unlock passkey phrase (settings: `UIMode_passkey`), this message will not adjust.
I am thinking of introducing that, if anyone thinks that is worthwhile.
2. The string is in ASCII, and the font we use does not support the arrow unicode characters, so its kind-of 'wordy' right now.
=> Add confirmation popup when changing to UI mode Kid or Kiosk.

CMake/Packages/FindlibCEC.cmake, CMakeLists.txt, es-app/src/main.cpp, es-core/CMakeLists.txt, es-core/src/CECInput.cpp, es-core/src/CECInput.h, es-core/src/InputConfig.cpp, es-core/src/InputConfig.h, es-core/src/InputManager.cpp, es-core/src/InputManager.h, es-core/src/guis/GuiDetectDevice.cpp
Implemented optional CEC support.
If CMake can't find libcec.so then it will just build without CEC support.
It's configured the same way as a keyboard.
The FindlibCEC.cmake might be wrong, first time I've written one of those, I based it on the one for FreeImage ( I think ).
Have tested this on my rpi3 with my Sharp TV and it worked just fine for me.
I'm happy to answer any questions.
=> CEC Support

es-core/src/StringUtil.h, es-core/src/components/TextComponent.cpp, es-core/src/components/TextEditComponent.cpp, es-core/src/resources/Font.cpp, es-core/src/resources/Font.h
Moved some functions from Font to StringUtil.h and optimized / improved them where possible
Font::readUnicodeChar -> StringUtil::chars2Unicode
Font::getNextCursor -> StringUtil::nextCursor
Font::getPrevCursor -> StringUtil::prevCursor
Font::moveCursor -> StringUtil::moveCursor
And I added StringUtil::unicode2Chars which takes a unicode hex and turns into into a std::string, @zigurana might want that for https://github.com/RetroPie/EmulationStation/pull/295
All the functions was tested on the VR Virtua Racing and Doom Japanese descriptions provided in https://github.com/RetroPie/EmulationStation/pull/269 and by editing them inside ES and stepping forward / backwards to trigger the nextCursor and prevCursor.
Edit: A little bit to quick, too much code at once, forgot to test this on the pi. …
=> Implement StringUtil ( Unicode )

es-core/src/CECInput.cpp
Needed for Raspbian stretch.
So far, only compile-tested, no build warnings. Unfortunately, when I try to hold a remote button to configure input, "CEC" appears grayed and disappears; it seems that my TV's CEC implementation doesn't support long-press, so the code may need changing to work for me.
pinging @tomaz82
=> Implement libcec4 compatibility

es-app/CMakeLists.txt, es-app/src/FileFilterIndex.cpp, es-app/src/guis/GuiGamelistFilter.cpp, es-app/src/guis/GuiGamelistOptions.cpp, es-app/src/guis/GuiMenu.cpp, es-app/src/views/SystemView.cpp, es-app/src/views/UIModeController.cpp, es-app/src/views/UIModeController.h, es-app/src/views/ViewController.cpp, es-app/src/views/ViewController.h, es-app/src/views/gamelist/BasicGameListView.cpp, es-app/src/views/gamelist/ISimpleGameListView.cpp, es-core/src/Settings.cpp, es-core/src/Window.cpp, es-core/src/Window.h, es-core/src/resources/Font.cpp
Refactoring: Split PasskeyListener and UI mode monitoring into new separate class: UIModeController (singleton).
The UIMode code started to end up in too many different locations for my liking, so I practiced implementing a singleton class for it.
The one functional improvement this brings, is that the passkey phrase (as reported by the new popup when changing the UI mode) is now pulled from the passkey actually stored in `settings.xml`:
Otherwise, this PR should have no functional changes.
I have one open question for anyone with an interest in this:
I was trying to insert the unicode glyph for the arrow symbols [here](https://github.com/RetroPie/EmulationStation/compare/master...zigurana:UIModeController?expand=1#diff-421a7ab70595f4ab3f599b564ab2a298R102), but I have no idea how to get …
=> [Ready to Merge] UIModeController Class

es-app/src/views/gamelist/BasicGameListView.cpp
Regression somewhere down the line when we explicitly set typecasts here.
Fixes #317.
By the way, sometime between 2.6.0 and now, we've also broken the systemview for empty collections, in that they do not show up even though they're enabled.
I'll try to bisect that.
Should be safe to merge, really.
=> Fixes favorites crashing when removing last entry

es-app/src/FileData.cpp, es-app/src/FileSorts.cpp, es-app/src/MetaData.cpp, es-app/src/MetaData.h, es-app/src/scrapers/GamesDBScraper.cpp, es-core/CMakeLists.txt, es-core/src/Util.cpp, es-core/src/Util.h, es-core/src/components/DateTimeComponent.cpp, es-core/src/components/DateTimeComponent.h, es-core/src/utils/TimeUtil.cpp, es-core/src/utils/TimeUtil.h
Utils::Time gives us both a replacement for handling DateTime, and a way to measure the duration between 2 DateTime's, it does this at a much lower footprint than boost::date_time does.
What DateTime also does is that it always knows the time_t ( seconds since 1970 ), struct tm ( tm_min, tm_mday and so on ) and isoString ( "20171128T204700" ), so no need to convert between those 3. It can take any of those 3 as input to the DateTime ctor.
=> Replaced boost::posix_time with Utils::Time

es-app/src/main.cpp, es-core/src/Renderer.h, es-core/src/Renderer_draw_gl.cpp, es-core/src/Renderer_init_sdlgl.cpp, es-core/src/Settings.cpp, es-core/src/Window.cpp, es-core/src/Window.h
Basically implemented this:
https://github.com/RetroPie/EmulationStation/issues/322
=> Implement --screensize and --screenoffset

es-core/src/components/VideoVlcComponent.cpp
Issue: With `VideoAudio` set to `false` in the es_settings.cfg file, the VLC player was only muting the audio on the first play of the video, but not upon looping.
```
libvlc-dev/artful,now 2.2.6-6 amd64
libvlccore-dev/artful,now 2.2.6-6 amd64
```
This fix reapplies the mute setting for each loop.
=> Fix: VLC player not muting audio after first loop

es-core/src/ThemeData.cpp
Fixes a bug introduced in #333.  Reported in the [forums](https://retropie.org.uk/forum/topic/7156/variable-support-in-themes-in-emulationstation/79).
Theme variables were only resolving the first variable in a given value.  This was breaking the snes-mini theme.  For the example below only the `${region}` variable was resolved.
```
<path>./art/icons${region}/${system.theme}.png</path>
```
@tomaz82, let me know if you have any suggestions on a better way to implement this.
=> fix resolvePlaceholders to handle multiple variables in a single string

es-app/src/FileData.cpp, es-app/src/PlatformId.cpp, es-app/src/PlatformId.h
After profiling UI filtering and startup I determined that getCleanMameName was responsible for the incredibly long load times when loading/filtering Mame ROMs. This function was using a linear search over a pre-sorted array to find a corresponding Mame ROM Name from the ROM name. It now uses a binary search which improves UI load/filter responsiveness by a couple orders of magnitude.
Single core performance on my i7 for 10,000 iterations was 2.01 secs vs
7.77e-4 secs. I've been testing for a few days now and wow, night & day difference with large ROM libraries.
=> Majorly improved performance when fetching Mame names.

DEVNOTES.md, README.md
I want to preface this PR with the fact that I am not a C++ developer, just an EmulationStation enthusiast.
It seems that the dependency on Eigen3 has been removed as of PR #263, this just cleans up the README and a single documentation file where Eigen was still mentioned.
=> Update README to reflect Eigen3 dependency removal

es-app/src/main.cpp, es-core/src/Renderer.h, es-core/src/Renderer_draw_gl.cpp, es-core/src/Renderer_init_sdlgl.cpp, es-core/src/Settings.cpp, es-core/src/components/VideoPlayerComponent.cpp
Basically does what display_rotate does in config.txt, except doing it for ES only, and without the penalty that comes with doing a 90 or 270 degree rotation using display_rotate. This also works for platforms that doesn't allow to have the OS or whatnot to do the rotation.
It maps the same as display_rotate
--screenrotate 0 == nothing
--screenrotate 1 == 90 degrees
--screenrotate 2 == 180 degrees
--screenrotate 3 == 270 degrees
Only tested with default Carbon theme which looks "ok" but obviously wrong in the case of 1 and 3, will need a theme made for a reversed aspect ratio ( 9/16 instead of 16/9 if using a 16/9 screen )
Thanks to @zanac who did the first part
=> Add support for --screenrotate

es-app/src/CollectionSystemManager.cpp
Removing and adding entry to index when adding/removing favorites.
Should fix the case of updating the filters list when there are no favorites and they're added via pressing Y.
Should fix #349 .
The fact that Favorites don't show up when empty is being handled in #325 , together with the rest of the collections.
=> Fixing first favorites not updating index

es-app/src/CollectionSystemManager.cpp, es-app/src/FileData.cpp, es-app/src/Gamelist.cpp, es-app/src/SystemData.cpp, es-app/src/SystemScreenSaver.cpp, es-app/src/main.cpp, es-app/src/scrapers/Scraper.cpp, es-app/src/views/gamelist/BasicGameListView.cpp, es-app/src/views/gamelist/VideoGameListView.cpp, es-core/src/HttpReq.cpp, es-core/src/InputManager.cpp, es-core/src/Settings.cpp, es-core/src/ThemeData.cpp, es-core/src/Util.cpp, es-core/src/components/VideoComponent.cpp, es-core/src/guis/GuiDetectDevice.cpp, es-core/src/resources/ResourceManager.cpp, es-core/src/utils/FileSystemUtil.cpp, es-core/src/utils/FileSystemUtil.h
Replace some boost functionality with Utils::FileSystem, this is just step 1 of many to eliminate boost::filesystem
=> boost::filesystem replacement, step 1

es-app/src/CollectionSystemManager.cpp, es-app/src/Gamelist.cpp, es-app/src/SystemData.cpp, es-app/src/SystemScreenSaver.cpp, es-app/src/main.cpp, es-app/src/scrapers/Scraper.cpp, es-core/src/InputManager.cpp, es-core/src/Log.cpp, es-core/src/Settings.cpp, es-core/src/ThemeData.cpp, es-core/src/components/VideoComponent.cpp, es-core/src/platform.cpp, es-core/src/platform.h, es-core/src/utils/FileSystemUtil.cpp, es-core/src/utils/FileSystemUtil.h
Replace the last traces of boost::filesystem::operations, this is PR 4 of 5 in the boost::filesystem removal quest
=> Replace the last usage of boost::filesystem::operations

es-app/src/CollectionSystemManager.cpp, es-app/src/views/gamelist/VideoGameListView.cpp
Fix thumbnail and image to be separated as I think it was originally meant to be.
The current implementation for VideoViewis that md_video can show a thumbnail before fading to the video.
This is specified with <thumbnail> tag in the metadata, or if that doesn't contain a valid image, it tries with <image>.
Ontop of this a theme can still have the md_image element, which is where I believe the current implementation is broken, because that one will also use thumbnail, where I believe it should only use what's specified in <image>. So that the video thumbnail in md_video, and the actual md_image element, can be 2 different textures. I'm thinking screenshot maybe for the thumbnail, and boxart for the image. Current code would use the screenshot on both elements.
Anyway, long description. …
=> Fix thumbnail and image to be separated

es-core/src/utils/FileSystemUtil.cpp
Fix start and offset not being reset for each invalidChar tested in Utils::FileSystem::getEscapedPath
=> Fix Utils::FileSystem::getEscapedPath

es-core/src/components/VideoPlayerComponent.cpp
mStaticImage on the OMX player was incorrectly using setSize when it should use setResize
Scenario:
Theme that has md_video setup using `<size>` and not `<maxSize>`
omx player used ( hardware video playback )
using delayed video, or missing video
In this specific scenario the video thumbnail would be displayed using the wrong size
=> Fix mStaticImage to use setResize

es-app/src/guis/GuiMenu.cpp
As topic says, launch with --debug and the "start" menu now shows not only build number, but also build date and time
=> Show build date and time when starting ES with --debug

es-core/src/utils/FileSystemUtil.cpp
Fix getDirContent to not have a double //, so filesnames don't come back as "/filename.ext".
This fixes custom collections.
=> Fix double //

es-core/src/utils/FileSystemUtil.cpp
Similar fix to what jrassa suggested in https://github.com/RetroPie/EmulationStation/pull/378
This also adds the fallback to use current working directory if no homepath is found.
=> Fix getHomePath crash when the environment variable isn't set

es-app/src/CollectionSystemManager.cpp, es-app/src/CollectionSystemManager.h
Quite a bit of feedback had accumulated about the Last Played list not having a limit.
After the discussion over at 
https://retropie.org.uk/forum/topic/16559/last-played-collection-possible-to-limit
I implemented a limit of 50 for the Last Played view, instead of letting it run indefinitely.
I tested it for the most common edge cases I could think of and squashed any apparent bugs, but the usual considerations apply.
=> Limiting Last Played view to the last 50 games you played

es-core/src/utils/FileSystemUtil.cpp
@Tomaz82 , just for sanity checking, could you double check that this change does not compromise what the original intention for the function was?
///
Fix for common path detection that was messing up metadata writing.
Reference: http://www.cplusplus.com/reference/string/string/find_first_of/
It was being used to match the entire string, but in reality what it does is "Notice that it is enough for one single character of the sequence to match (not all of them). See string::find for a function that matches entire sequences".
=> Fixing common path detection

es-core/src/utils/FileSystemUtil.cpp
Fixing path handling for Collection files after boost extermination on the Pi. The output for `Utils::FileSystem::getDirContent()` was returning the path with two slashes, which resulted in no files being recognized as the format wasn't understood.
@tomaz82 any concerns with this specific change? You had it for Windows as well, so just want to make sure I'm reading things right.
Thanks.
=> Fixing path generation on the Pi for getDirContents

.gitignore
When opening this project with Clion, it automatically generate all the following files : 
```
.idea/codeStyles/Project.xml
.idea/EmulationStation.iml
.idea/markdown-exported-files.xml
.idea/markdown-navigator/profiles_settings.xml
.idea/markdown-navigator.xml
.idea/misc.xml
.idea/modules.xml
.idea/.name
.idea/vcs.xml
.idea/workspace.xml
CPackConfig.cmake
CPackSourceConfig.cmake
emulationstation-all.cbp
es-app/emulationstation.cbp
es-core/core.cbp
external/nanosvg/nanosvg.cbp
```
Can you please merge the 3 lines I added to the .gitignore into your fork, this would make my life a lot easier when working on this project.
=> Add automatically generated Clion files to gitignore

.gitignore
@Koerty accidentally excluded all .cmake files instead of the specific files that Clion generated, and was getting in my way of developing a new feature... So, I fixed it. BTW, no offence, @Koerty.
=> Fixed a quirk in the Clion PR

es-core/src/components/ImageGridComponent.h
Renamed variables gridSize to gridDimension and function getGridSize to getGridDimension in ImageGridComponent.h, as suggested by @zigurana in the complete grid view pull request.
This may look a bit overkill to create a pull request just for this but it add way too much noise to the next pull request (Step 3 : Rewrite the grid view display code written by Aloshi https://github.com/RetroPie/EmulationStation/issues/389) which is already big enough. So I'm ready to sacrifice this on the altar of pull request clarity.
=> [GRID] Rename gridSize to gridDimension in ImageGridComponent.h

es-app/src/guis/GuiMenu.cpp, es-app/src/views/ViewController.cpp, es-app/src/views/ViewController.h, es-app/src/views/gamelist/GridGameListView.cpp, es-app/src/views/gamelist/GridGameListView.h, es-core/src/ThemeData.cpp
Point 2 of the gridview's roadmap https://github.com/RetroPie/EmulationStation/issues/389
The grid view is now enabled but hidden for easier reviews and testing of the next pull requests. To enable it, you need to manually tweak the file es_settings.cfg by changing the value of GamelistViewStyle, using the command below for example : 
```bash
sed 's!<string name=\"GamelistViewStyle\" value=\"[a-zA-Z]*\" />!<string name=\"GamelistViewStyle\" value=\"grid\" />!' ~/.emulationstation/es_settings.cfg -i
```
It does not show yet in the menu (UI settings > Gamelist view style) so you can't set the view type to grid here but you can revert it to basic/detailed/video.
If you enabled the grid view by manually editing the config file and leave the "UI settings" menu without selecting any of this …
=> [GRID 2] Enable the grid for developers

es-app/src/views/gamelist/GridGameListView.cpp, es-core/src/components/ImageGridComponent.h
**Description**
This PR is the Step 3 of the roadmap https://github.com/RetroPie/EmulationStation/wiki/Gridview-Roadmap-and-FAQ#roadmap
It rewrite the display code of the grid view, using a "tileMaxSize" variable as suggested by @jrassa on https://github.com/RetroPie/EmulationStation/issues/206#issuecomment-326809971
**Complete changelog**
- Add 3 new attributes to ImageGridComponent.h : mMargin, mTileMaxSize and mSelectedTileMaxSize, which themes will be able to configure starting at step 6 (see the roadmap)
- Rewrite the tile positioning
- Update the "render" function, so the selected tile is displayed on top of the others (until now the selected tile size wasn't configurable and was = tile size + margin so it couldn't overlap the others)
**Screenshots**
Screenshot of the grid with the …
=> [GRID 3] Rewrite the grid view display code

es-core/src/components/ImageComponent.cpp
Fix a small typo which have been here since Aloshi introduced fliping images in October 2012 the 8th, but nobody ever noticed or cared about the poor vertical flip function :')
Bug
Fix
=> Fix ImageComponent flipY

es-app/src/guis/GuiMenu.cpp
From within a collection that'll no longer be present at the carousel level.
@tomaz82 can you test if it fixes the issue you reported at the time when changing theme?
Thanks.
=> Fix crash when changing theme 

es-app/src/views/gamelist/BasicGameListView.cpp, es-app/src/views/gamelist/BasicGameListView.h, es-app/src/views/gamelist/GridGameListView.cpp, es-app/src/views/gamelist/GridGameListView.h, es-app/src/views/gamelist/ISimpleGameListView.cpp, es-app/src/views/gamelist/ISimpleGameListView.h
Point 1 of the gridview's roadmap (1.1 and 1.2 not included) https://github.com/RetroPie/EmulationStation/issues/389
- Allow quick system swap using left/right shoulder in all game view (grid, detailed, basic, video)
- Add left and right shoulder to the help prompt of the grid view
The quick system swap using left/right shoulder is enabled for **all** game views but is only showed up in the help prompt of the grid view.
Help prompt of the Grid view before changes
Help prompt of the Grid view after changes
Help prompt of Basic/Detailed/Video view (no changes)
=> [GRID 1] Allow quick system swap using left/right shoulder

es-app/src/views/gamelist/GridGameListView.cpp
Update the populateList function of the GridGameListView to mimic the changes made by @pjft in BasicGameListView when he introduced custom game collections : 
- Call the addPlaceholder function if grid is empty
- Set the header text (system name)
=> [GRID FIX] Update the populateList function of the GridGameListView

THEMES.md, es-app/src/views/gamelist/GridGameListView.cpp, es-app/src/views/gamelist/GridGameListView.h, es-core/src/components/ImageGridComponent.h
- Add the metadata from the detailed view to the grid view (minus the image, as it doesn't make sens in the grid view)
- Add a callback to ImageGridComponent to update the metadata info panel when cursor changed
=> [GRID 4] Add metadata from the detailed view to the grid view

THEMES.md, es-app/src/views/gamelist/GridGameListView.cpp, es-core/src/ThemeData.cpp, es-core/src/components/ImageGridComponent.h
**Changes**
**EDIT : removed "margin, tileMaxSize, selectedTileMaxSize" for now**
- The themes can now configure following elements : pos, size
- Change some default values for them
**Testing**
You can test by using [my custom test theme](https://github.com/Koerty/es-theme-test-gridview), it had a green border around the grid so you can better see what's going on (like on the screenshots of my [previous PR](https://github.com/RetroPie/EmulationStation/pull/396)).
Or using this modified version of @lilbud Material theme : [here](https://github.com/Koerty/es-theme-material)
Or by creating a new theme.xml from this : 
```xml
<theme>
<formatVersion>4</formatVersion>
<view name="grid">
<imagegrid name="gamegrid">
<pos>0.1 0.1</pos>
<size>0.8 0.8</size>
</imagegrid>
</view>
</theme>
```
If a …
=> [GRID 3.2] Add base theming syntax for the grid

es-app/src/views/gamelist/BasicGameListView.cpp, es-app/src/views/gamelist/GridGameListView.cpp, es-app/src/views/gamelist/ISimpleGameListView.cpp
What is the use case behind this ? You don't go in the retropie menu to randomly toy around with the settings, so I disabled it.
=> Disable random game selection in retropie settings menu

THEMES.md, es-app/src/views/gamelist/GridGameListView.cpp, es-core/CMakeLists.txt, es-core/src/ThemeData.cpp, es-core/src/components/GridTileComponent.cpp, es-core/src/components/GridTileComponent.h, es-core/src/components/ImageGridComponent.h
This is biggest PR I created yet (since I started to completely disassemble the grid view), so take a big breath before you dive into the code.
**Changelog**
- Add the GridTileComponent which hold the image and its background
- Add base theming syntax for the ImageGrid and GridTile
- Numerous refactoring/cleaning in ImageGridComponent
- GridDimension is not recalculated dynamically, we don't need that with new grid display algorithm, so we just (re)calculate it when ImageGridComponent got instantiated or after theme changed
- The ImageGridComponent control the GridTiles only using setImage, setSelected and setVisible, all the tile parameters (max size, image color, ...) are stored inside the GridTileComponent class
- Moved all the maths for calculating the start position (the number of …
=> Add GridTileComponent and base theming syntax

es-core/src/GuiComponent.h, es-core/src/components/ImageComponent.cpp, es-core/src/components/ImageComponent.h
This operations will be needed by the grid later on the road so I better submit the changes now in its own pull request.
This add new methods to the class ImageComponent:
```c++
void setMinSize(float width, float height);
void setMinSize(const Vector2f& size);
void cropLeft(float percent);
void cropTop(float percent);
void cropRight(float percent);
void cropBot(float percent);
void crop(float left, float top, float right, float bot);
void uncrop();
```
Usage examples : 
- A call to cropTop(0.2) will crop 20% of the top of the image
- A call to minSize(0.2, 0.2) will resize the image smallest side to 0.2 without breaking aspect ratio, but crop the extra lenght of the biggest side.
- Call minSize(0.2, 0.2) and then uncrop() to define an image size by its smallest side
=> Add cropping and minSize to ImageComponent

es-app/src/CollectionSystemManager.cpp, es-app/src/FileData.cpp, es-core/src/utils/FileSystemUtil.cpp, es-core/src/utils/FileSystemUtil.h
This fixes 2 issues reported recently by Windows users.
https://retropie.org.uk/forum/topic/16760/custom-collections-are-not-showing-in-emulationstation-for-windows
https://github.com/jrassa/EmulationStation/issues/7
=> fix for several small issues in Windows build

es-core/src/components/ImageGridComponent.h
The function calcGridDimension should be called **after** mScrollDirection is set (because it rely on it).
This is a small issue I overlooked when I rebased #411 after #408 got merged.
=> Fix calcGridDimension being called before mScrollDirection

THEMES.md, es-app/src/views/gamelist/DetailedGameListView.cpp, es-app/src/views/gamelist/DetailedGameListView.h, es-app/src/views/gamelist/GridGameListView.cpp, es-app/src/views/gamelist/GridGameListView.h, es-app/src/views/gamelist/VideoGameListView.cpp, es-app/src/views/gamelist/VideoGameListView.h
Unlike the others, it is by default positioned offscreen.
I was going to add the md_name metadata field to the grid view when I were asked by multiple people to add it to all views, so here we go.
=> Add the new metadata field md_name to grid video and detailed views

THEMES.md, es-core/src/HelpStyle.cpp, es-core/src/HelpStyle.h, es-core/src/ThemeData.cpp, es-core/src/components/HelpComponent.cpp
This have been asked multiple times by theme makers on the forum or here #224
=> Add "origin" theming element for help prompt

es-app/src/FileData.cpp, es-app/src/FileData.h, es-app/src/FileSorts.cpp, es-app/src/MetaData.cpp, es-app/src/guis/GuiGamelistOptions.cpp
This is in response to people wanting to sort "The Legend of Zelda" as "Legend of Zelda" alphabetically without dropping the "The" in the displayed name.  It also allows sorting Final Fantasy VII and IX, as "7" and "9" without changing the displayed title.
=> add sortname to gamelist.xml to sort by a different name

es-core/src/components/NinePatchComponent.cpp, es-core/src/components/NinePatchComponent.h
**Changes**
- Rewrite NinePatchComponent to handle images with a different size than 48x48 px
- It's now possible to change the border sizes using setCornerSize function
**Context**
Since the grid view use the NinePatchComponent for the tile background, it would be nice to be able to use images of different size than 48x48 pixels.
The current code was badly written as the part sizes and coordinates were sometimes calculated using the Vector2f returned by getCornerSize, sometimes using the "Vector2f pieceCoords[9]". It would have taken me more time to update it than rewrite it from scratch, so I did.
**Examples**
Using this image : 
The following examples have their borders colored (remember the setEdgeColor) in red so you better see what's going on.
Corner size : 8 8
Corner size : 16 16 …
=> Rewrite NinePatchComponent to handle images of all sizes

THEMES.md, es-core/src/ThemeData.cpp, es-core/src/components/GridTileComponent.cpp, es-core/src/components/GridTileComponent.h
Add 3 new theming properties to the grid tile background : 
- backgroundCornerSize
- backgroundCenterColor
- backgroundEdgeColor
@jrassa This is the last step before the release of the V1 of the grid view with PR 418 and 419, the finish line is in sight, stay strong ;)
=> Add 3 new theming properties to the grid tile background

es-core/src/Window.cpp, es-core/src/components/ImageGridComponent.h
This is a pretty big task, so I created this PR before it's finished so you can take a first look and give me some feedback if you want to. It is not completely stable, as it still have some bugs or unintended behaviors (list at the end of this message), but the base mechanics are already here and working as intended.
I rewrote the dynamic image loader from scratch, trying to make a simpler version than the original one, sadly, it isn't possible, you will understand why very soon.
The dynamic image loader aim to load just the textures displayed on the screen + 1 extra row on top and on the bottom, so the user is less likely to see the magic happening.
For this, I used 2 var : **target min range** and **target max range**, those are updated every time the grid scrolled up or down (which …
=> [GRID 7] Dynamic image loader

es-app/src/guis/GuiMenu.cpp
Beside step 7, all the base features are now included in the grid view.
Once step 7 will be done, the grid will be considered stable, reliable and mature enough, to release a  V1, and so to open the door to everyone using emulationstation-dev, by merging this.
This doesn't mean the development is over, I have big plans for the future of the grid view, but those are just embellishments, all the base features are here.
You can check the ![wiki](https://github.com/RetroPie/EmulationStation/wiki/Gridview-Roadmap-and-FAQ#unordered-extra-features) to see what may come after the first grid view release.
=> [GRID 8] Enable the grid view for everyone

es-core/src/components/ImageComponent.cpp
This should fix for the most part an annoying image resize flicker that had been discussed in the forums in the past and seemed to have cropped up several versions back.
I added some safety code for minSize as well, which should also at least mitigate the issue there if present.
=> Fix for image resize flicker when using MaxSize

es-core/src/components/ImageGridComponent.h
This fix 2 bugs with the horizontal scrolling grid :
- The grid is now positioned correctly (bug introduced by the buffer of the dynamic image loader)
- The right column contain the partial tile in horizontal mod, not the bottom row
=> Fix horizontal scrolling grid bugs

es-core/src/components/GridTileComponent.cpp, es-core/src/components/ImageGridComponent.h
This fix the infinite freeze with big game collections by storing the texture path instead of loading texture resource.
Sadly this make navigating into the grid a bit laggish at highest scroll speeds with big game collections, I'm looking at different solutions to solve this problem but I think it's out of the scope of this PR.
=> Grid fix freeze with big game collections

es-core/src/components/OptionListComponent.h
* fixes #447 
* but not #452
The problem is that when the SVG file is loaded, it is first set to the SVG's internal dimensions and *then* to the desired dimensions, stumbling over a possible race condition while doing so. The workaround here is to set the desired dimensions *before* loading the SVG, thus avoiding the intermediate step.
=> Fix SVG resize issue for option_arrow.svg

es-core/src/utils/FileSystemUtil.cpp
This should fix https://github.com/RetroPie/EmulationStation/issues/473 and any other issues with path's ending with a /
Only tested on Windows, and I would appreciate if someone could test this on a pi since I currently don't have one
=> Remove trailing '/' on paths in getGenericPath

es-core/src/utils/FileSystemUtil.cpp
pi: #define _FILE_OFFSET_BITS 64
windows: Switch to use stat64 where needed
Tested with a 2.9GB rom on:
Windows 7
Ubuntu 16.04
Pi3
=> Fixes for roms larger than 2GB

es-app/src/SystemData.cpp, es-app/src/guis/GuiMenu.cpp
This also moves the hidden files skip to happen earlier
Previously it only checked if a file was hidden if it matched the extension for the current system tested, this means that most of the time, it also loops over the media folder, and all the files in that, which for systems like mine, is ALOT, currently 8 media file per rom, and for GBA alone thats over 8000 media files, that it scans and loops over.
With this check moved earlier, I could mark the media folder as hidden ( renamed it .media ) which means it skips the entire folder right away.
Now, on my local SSD this made absolutlely no difference whatsoever, so I decided to test the worst case scenario, having everything on a network storage, ES bootup times went from 340 seconds to 55 with this simple change.
=> Allow to show hidden files on Windows

es-app/src/CollectionSystemManager.cpp
The getGenericPath fix broke custom collections, this once again fixes that.
=> Fix missing / in custom collection path

es-core/src/ThemeData.cpp
This was a commonly requested enhancement for variables in themes.  Turns out it was pretty simple to implement.
=> allow variables in import elements

es-core/src/guis/GuiInputConfig.cpp
[2nd attempt after #482, which was obviously wrong]
The Input Configuration dialog should show the 'hold-to-skip' message every time an button/input is considered skippable, instead of just displaying the info message just at the beginning of the Input Mapping. However, because of the way the color for the component was initialized, the `mColorOpacity` would be zero, so toggling the visibility of this TextComponent calls to `setOpacity` did not work.
Started by https://retropie.org.uk/forum/topic/2281/how-do-i-get-passed-the-gamepad-config-screen-with-keyboard/15.
=> Fix toggling the display of the hold-to-skip message during Input Configuration.

es-app/src/PlatformId.cpp
Since commit 3f3e1ceb16cea4186ef378abc33b1f5bbf330232, `mameNameToRealName` is no more used.
=> Removing no more used `mameNameToRealName`

es-core/src/InputManager.cpp, es-core/src/InputManager.h
Some drivers (such as hid-sony) configure analog triggers (L2/R2) as axes
with axis range -32768-32767, but the resting value starts at -32768,
causing an initial or light press to register erroneously as a minus
axis value.
Fix by shifting ABS_Z and ABS_RZ axes that are detected to rest at
-32768 so that they will range from 0-32767 instead.
Patch based on Jools Wills' earlier commit: https://github.com/RetroPie/EmulationStation/pull/58
--
N.B. Keep in mind that the hid-sony driver introduces additional complexity by way of also exporting digital button events for L2/R2. I've addressed that issue by adding a patch to customhidsony via the sixaxis PR: https://github.com/RetroPie/RetroPie-Setup/pull/2263
This PR combined with the sixaxis PR seems to result in everything working properly, …
=> InputManager: improve trigger axis calibration

es-app/src/views/gamelist/BasicGameListView.cpp, es-core/src/Settings.cpp
On PR #435 we've worked to make an unattended (aka arcade) mode, hiding several controls from Kids mode and adding a toggle to force display all games (even the non kid ones).
But, later, some commit changed the BasicView to display again the Favorites controls in Kids mode.
Additionally I've noticed that while working on #435 I've included `ForceDisableFilters` in settings to be not saved, which doesn't make sense.
=> Fixing kids/unattended mode

es-app/CMakeLists.txt, es-app/src/PlatformId.cpp, es-app/src/PlatformId.h, es-app/src/components/ScraperSearchComponent.cpp, es-app/src/guis/GuiMenu.cpp, es-app/src/scrapers/Scraper.cpp, es-app/src/scrapers/Scraper.h, es-app/src/scrapers/ScreenScraper.cpp, es-app/src/scrapers/ScreenScraper.h, es-core/src/utils/StringUtil.cpp, es-core/src/utils/StringUtil.h
I've added a new scraping source in Emulationstation - ScreenScraper.fr. 
The new scraper is loosely based on the existing TGDB scraper source, but the API is a bit different. Some comments about this new module
* ScreenScraper doesn't seem to have a 'search game' function in the api. A search request for a game should contain the ROM name and a checksum - so that matching would work better. Right now the module only searches by name. 
The result is that scraping would only return 1 result max (ideally the ROM itself), unlike TGDB that could return a list and the user could decide which result would import.
I plan to add checksum support, but right now there isn't one.
* The PR appears in GH as 'Can't automatically merge' because of the commits yesterday in the `PlatformId` files - but I …
=> Add ScreenScraper.fr as scraping source

es-app/src/FileFilterIndex.cpp, es-app/src/views/UIModeController.cpp, es-app/src/views/UIModeController.h
This fixes games marked both as hidden and kid not being shown in Kid mode.
Reported in https://retropie.org.uk/forum/topic/20867 (original discussion on Reddit [here](https://old.reddit.com/r/RetroPie/comments/agp78y)).
=> Fix Kiosk mode filters applying also to Kid mode

es-core/src/Settings.cpp
This adds the default value that was missing from the changes in #460, which avoids a crash when opening the menu and should also ensure that the audio keeps working in an upgrade scenario.
=> Fix for unset AudioCard setting

es-app/src/main.cpp, es-app/src/views/ViewController.cpp, es-core/src/Settings.cpp, es-core/src/Window.cpp, es-core/src/Window.h
Starting up emulationstation takes me about 1 minute over the network
with a large collection of 27 systems with images.
This patch uses the loading screen to tell the user about the status
of the startup, with information how many systems are left for view
initialization.
The most beefy part of the startup process is initializing the views,
and preloading images.
This patch extends the `renderLoadingScreen` function to take a string
and uses it in `ViewController::preload`.
=> Loading screen: Be more verbose about what is happening.

es-app/src/scrapers/ScreenScraper.cpp
Seems searching by game name is not working reliably - anymore -, use the full filename until we add checksum to the search.
Sorry for not catching this sooner.
=> Fix ScreenScraper search by filename

es-app/src/FileData.cpp
This seems to fix the problems reported in the forum (https://retropie.org.uk/forum/topic/21216, https://retropie.org.uk/forum/topic/21227/ and I'm sure there's at least another one). 
`getThumbnailPath` returns an empty string when `LocalArt` is not enabled and then the **thumbnail** tage is empty, but it should look at the **image** tag also, regardless of `LocalArt` setting.
I would appreciate some testing, I only tested this on Windows where I don't have videos.
=> Fix "getThumbnailPath" ignoring the 'image' tag when 'LocalArt' is not set

GAMELISTS.md, README.md
* added the info for the new `rapidjson` dependency and updated the CLI output.
* added the info about the `video`, `sortname` and `thumbnail` to the gamelist format.
I noticed some of the CLI options don't show in the help message (i.e. `--rotate`), but that can probably be corrected in another PR.
=> docs: minor documentation formatting and updates

es-app/src/VolumeControl.cpp
Stumbled on this while tested other things.
If you open "Sound Settiings" multiple times and do not change the system volume and your audio device has a small range (mine: minVolume 0 to mavVolume 151) the system volume in the dialog gets rounded down each time you open the dialog.
=> Fixed rounding.

es-app/src/SystemScreenSaver.cpp, es-app/src/SystemScreenSaver.h, es-core/src/Window.cpp, es-core/src/Window.h
Change screensaver handling (counting and choosing) to use FileData data (i.e. games that actually exist and are loaded) rather than gamelist data (and XML).
Performance is improved (well, not really noticeable).
Tested image and video screensaver.
=> Change handling of screensaver to FileData only

resources/mamebioses.xml
Some of the BIOS files that came with my MAME rom set were not hidden in the rom list, so I'd like to add them to the bios xml.
=> Extend list of MAME BIOS files to hide

es-app/src/Gamelist.cpp, es-core/src/utils/FileSystemUtil.cpp, es-core/src/utils/FileSystemUtil.h
Fixed the bug with iEquivalent by eliminating the need for it entirely, now makes both paths canonical and compares  them
=> Fix FilesystemUtil::isEquivalent by eliminating it entirely

es-app/src/FileData.cpp, es-app/src/guis/GuiMenu.cpp, es-core/CMakeLists.txt, es-core/src/InputManager.cpp, es-core/src/Scripting.cpp, es-core/src/Scripting.h, es-core/src/Settings.cpp, es-core/src/Window.cpp, es-core/src/platform.cpp
This is something I put together a while back and never finished up.  It was inspired by scripting supporting in [Pegasus](http://pegasus-frontend.org/docs/user-guide/scripting/) but with a few additional events that I thought could be useful.
draft wiki documentation for events can be found [here](https://github.com/jrassa/EmulationStation/wiki/Scripting).
=> implement scripting support

es-core/src/InputManager.cpp, es-core/src/InputManager.h, es-core/src/guis/GuiInputConfig.cpp, es-core/src/guis/GuiInputConfig.h
The hid-sony driver has both analog and digital buttons for the triggers,
and the analog values range from -32767 to 32767, which can cause two unwanted
input events (digital button and negative axis) per press.
Implement a function to filter out unwanted input events during configuration,
but isolate detection to known PS3 controllers with 6 axes so that older versions
of hid-sony and the sixad driver (which use 25+ axes) are not impacted negatively.
=> Implement filterTrigger for PS3 controllers

es-core/src/Window.cpp, es-core/src/Window.h
**Issue:** When pressing a button to cancel the screen saver, the underlying view would react to the input (A would launch the game, B would go to systems menu, etc.)
**Notes**
- I guess that's what the commented lines (142@145) originally intended to do;
- I noticed an `input` function in `SystemScreenSaver`: should the whole screen saver-handling block from `Window::input` go there instead?
=> [ScreenSaver] Consume input on cancel

CMakeLists.txt
This allows the detection RPi / Mali OpenGL ES libs & headers when you cross compile Emulationstation and and your sysroot != root.
=> CMakeList.txt: added CMAKE_FIND_ROOT_PATH for cross compiling

es-app/src/scrapers/ScreenScraper.h
ScreensScraper.fr has changed the SSL certificate, they now use a wildcard (*.screenscraper.fr) certificate. 
This makes the _screenscraper.fr_ hostname no longer available, so let's switch to `www.` for the API url. The change happened sometime around 20 April, but it doesn't seem to affect a lot of users.Apparently other scrapers haven't been using the non-www API endpoint.
=> Scraper: change ScreenScraper API URL

es-core/src/guis/GuiInputConfig.cpp, es-core/src/guis/GuiInputConfig.h
* Filter axes 2/5 for all devices, but only if LeftTrigger or RightTrigger is being configured. This should fix compatibility with XBox 360 and other generic controllers that use these axes for triggers, but won't affect other controllers using these axes for analog sticks, etc.
* Improve third-party PS3 detection (some Shanwan controllers have a grave accent in place of 'm' for 'Gamepad').
=> filterTrigger: generalize for more controllers

es-app/src/CollectionSystemManager.cpp
Emulationstation can crash when `UIMode` is set to Kid/Kiosk when removing entries from the 'Last Played' auto-collection, reported in [the forum](https://retropie.org.uk/forum/topic/22216/).
The crash occurs when the 'recent' list of played games is larger than _LAST_PLAYED_MAX_ (default: 50) and Emulationstation tries to remove from the list. If the filtered list size (i.e. only Kid/Non-hidden games) is less than the # of attempted removals, Emulationstation crashes because `getChildrenListToDisplay()` is practically empty.
=> Fix 'Last Played' collection crash.

es-app/src/views/gamelist/ISimpleGameListView.cpp
Had been broken a few months back.
Reported here:
https://retropie.org.uk/forum/topic/22564/favorites-in-kiosk-mode-are-not-working/
=> Fix Kiosk Favorites not registering

es-app/src/guis/GuiScreensaverOptions.cpp, es-app/src/guis/GuiScreensaverOptions.h, es-app/src/guis/GuiSlideshowScreensaverOptions.cpp, es-app/src/guis/GuiSlideshowScreensaverOptions.h, es-app/src/guis/GuiVideoScreensaverOptions.cpp, es-core/src/Settings.cpp, es-core/src/components/VideoPlayerComponent.cpp
This branch adds the ability for users to change the following features in OMX Player's subtitles (game info for screen saver).
- font size
- font file path
- italic font file path
- subtitle position
These changes can be made in the GUI menus via the Video Screen Saver menu, or directly in the es_settings.cfg file. Here's an example of the new keys loaded/saved into in the es_settings.cfg file:
- `<int name="SubtitleSize" value="38" />`
- `<string name="SubtitleFont" value="/usr/local/share/fonts/slkscr.ttf" />`
- `<string name="SubtitleItalicFont" value="/usr/local/share/fonts/slkscrb.ttf" />`
- `<string name="SubtitleAlignment" value="center" />`
Additionally safe, OMX Player defaults are hard-coded into EmulationStation application.
=> Add Game Info Font Settings to OMX Player

es-app/src/CollectionSystemManager.cpp, es-app/src/FileData.cpp, es-app/src/guis/GuiCollectionSystemsOptions.cpp, es-app/src/guis/GuiCollectionSystemsOptions.h, es-core/src/Settings.cpp
* adds a new configuration option ("CollectionShowSystemInfo" = bool). 
Can be toggled in the **Game Collections Settings** GUI - _SHOW SYSTEM NAME IN COLLECTIONS_. Defaults to previous behavior (true).
* reloads the Collections when the configuration is changed (same as with the other Collection settings change).
=> Collections: make the display of system's name configurable.

CMakeLists.txt
Useful when the VC4 legacy driver is not used for GLES (and OpenGL is used as `${GLSystem}`), but the usage of 'omxplayer' is still desired. It can be used when configuring the build, with:
```
cmake -DRPI:BOOL=On
```
=> add an option to force the compilation of Raspberry Pi video player bits

THEMES.md, es-app/src/components/RatingComponent.cpp, es-app/src/views/gamelist/DetailedGameListView.cpp, es-app/src/views/gamelist/GridGameListView.cpp, es-app/src/views/gamelist/VideoGameListView.cpp, es-core/src/GuiComponent.cpp, es-core/src/GuiComponent.h, es-core/src/ThemeData.cpp, es-core/src/ThemeData.h, es-core/src/components/ImageComponent.cpp, es-core/src/components/NinePatchComponent.cpp, es-core/src/components/ScrollableContainer.cpp, es-core/src/components/TextComponent.cpp, es-core/src/components/VideoComponent.cpp, es-core/src/components/VideoPlayerComponent.cpp, es-core/src/components/VideoVlcComponent.cpp
Add support for `visible` theme element.  Currently, to hide components, themes have to set position to offscreen.  This allows for easier hiding of components, as well as render logic will be skipped for hidden components.
=> support 'visible' theme element

es-core/src/guis/GuiInputConfig.cpp
So here's my fix for getting the proper configuration for the BigBen kid's PS3 #568.
I'm rather unsure that the HID name of the device is specific enough, so this patch uses the SDL GUID instead, which is supposedly unique for a hardware device type.
closes #568
=> Add BigBen kid's PS3 gamepad 146b:0902 to filterTrigger()

CMakeLists.txt
Well I had some trouble with some instabilities & random crashes related to libcec in the past. So I disabled it in a somewhat hacky way by simply patching it out:
```
--- a/CMakeLists.txt	2018-07-22 18:45:34.188603880 +0200
+++ b/CMakeLists.txt	2018-07-22 18:45:57.291577157 +0200
@@ -51,7 +51,6 @@
find_package(CURL REQUIRED)
find_package(VLC REQUIRED)
find_package(RapidJSON REQUIRED)
-find_package(libCEC)
#add ALSA for Linux
if(${CMAKE_SYSTEM_NAME} MATCHES "Linux")
```
This PR allows to disable libcec by adding `-DUSE_LIBCEC=OFF` to the CMake opts. It is enabled by default but I'm not sure if it should be mandatory or optional. So either:
`find_package(libCEC REQUIRED)`
or
`find_package(libCEC)`
because if the lib is missing on the target system & if it's not disabled build will fail.
=> CMakeList.txt: add option to disable libCEC / enabled by default

es-app/src/SystemScreenSaver.cpp, es-app/src/components/AsyncReqComponent.cpp, es-app/src/components/RatingComponent.cpp, es-app/src/components/ScraperSearchComponent.cpp, es-app/src/components/TextListComponent.h, es-app/src/views/SystemView.cpp, es-app/src/views/ViewController.cpp, es-core/src/Window.cpp, es-core/src/components/ButtonComponent.cpp, es-core/src/components/ComponentList.cpp, es-core/src/components/DateTimeEditComponent.cpp, es-core/src/components/ImageComponent.cpp, es-core/src/components/NinePatchComponent.cpp, es-core/src/components/SliderComponent.cpp, es-core/src/components/TextComponent.cpp, es-core/src/components/TextEditComponent.cpp, es-core/src/components/VideoVlcComponent.cpp, es-core/src/renderers/Renderer.cpp, es-core/src/renderers/Renderer.h, es-core/src/renderers/Renderer_GL21.cpp, es-core/src/renderers/Renderer_GLES10.cpp, es-core/src/resources/Font.cpp
Eliminate drawRect that takes int's and make sure everything uses the float version properly, this way everything is rounded the same way
Only round the transforms when setting them on the GPU, to make sure everything is rounded the same, but only at the final moment
=> Eliminate int drawRect and round all transforms

.github/ISSUE_TEMPLATE.md
Same wording as RetroPie-Setup. Wiki bit maybe not directly related to this repo, but both this and RetroPie-Setup repo get tickets that would be best started on the forum where more people can advise (eg. Issues that are due to user set-up).
=> added ISSUE_TEMPLATE.md from RetroPie-Setup to direct users to the forum first

es-core/src/components/GridTileComponent.cpp
Minor update to grid.  Fixes a bug reported on the forum.  gridtile properties were not being set properly.
=> fix assignment of gridtile theme properties

es-core/src/utils/FileSystemUtil.cpp
This prevents _getAbsolutePath_ to get into a loop with an empty path and EmulationStation to crash when `$CWD` is `/`.
=> getGenericPath: don't remove trailing '/' when path is '/'.

es-core/src/components/DateTimeEditComponent.cpp
If the display mode is `DISP_DATE`, ignore the `mTime` field when calculating the output. This influences the size calculation of the component.
Fixes https://github.com/RetroPie/EmulationStation/issues/385.
=> fix 'DateTimeEditComponent' output formatting

es-core/src/utils/FileSystemUtil.cpp
Same as my previous PR except following the same styling.  Also made a small change which uses std::string instead of a char buffer.
Basically uses platform-specific methods to retrieve the proper executable path location.
=> Use platform-specific methods for setExePath

es-core/src/renderers/Renderer_GL21.cpp, es-core/src/renderers/Renderer_GLES10.cpp
Cleaning up the GL 2.1 and GLES 1.0 renderers to be more similar to the upcoming GLES 2.0 renderer
Also adds error checking on most  GL calls if built in debug mode ( support for doing that is coming in another PR soon from @cmitu )
=> Prepare for GLES 2.0

CMakeLists.txt, README.md
Added the `_DEBUG` preprocessor define when generating a Debug build and updated the instructions for how to produce such build on Unix/Linux. 
Note that when the `cmake` generator supports multiple build profiles (like the MSVC generators), the _Debug_ profile will include the define automatically.
For now, it's used only by @tomaz82 in the upcoming renderer(s) refactoring (like #626).
=> cmake: define _DEBUG for Debug builds

es-app/src/components/TextListComponent.h, es-app/src/views/gamelist/GridGameListView.cpp, es-core/src/InputConfig.cpp, es-core/src/InputManager.cpp, es-core/src/components/ComponentList.cpp, es-core/src/components/DateTimeEditComponent.cpp
Create an alias (via `isMappedLike`) to accomodate existing configs that use the PageUp/Down buttons (should function as an alternative to https://github.com/RetroPie/EmulationStation/pull/562).
The RetroPie-Setup scripts map left/rightShoulder as `pageup`/`pagedown`, see [the mapping script](https://github.com/RetroPie/RetroPie-Setup/blob/595b09a9b44668727461da748382976dc8dc6b74/scriptmodules/supplementary/emulationstation/configscripts/emulationstation.sh#L50-L54), while EmulationStation maps them (natively) as `left` or `righshoulder`. 
To accomodate both, use `isMappedLike`, so existing RetroPie generated configs will work. In the future, we can replace the mapping produced by [emulationstation.sh](https://github.com/RetroPie/RetroPie-Setup/blob/master/scriptmodules/supplementary/emula …
=> InputManager: replace pageUp/Down with left/rightShoulder

es-app/src/scrapers/GamesDBJSONScraper.cpp, es-app/src/scrapers/GamesDBJSONScraperResources.cpp
Updates TheGamesDB API URL hard-coded within two scraper files to include "v1" within the path per note by Zer0xFF at https://forums.thegamesdb.net/viewtopic.php?f=5&t=1223
> for now, we're using a READ ONLY old backup, and the API is also back online,
> but using the prefix /v1/ which is both to get devs to explicitly make sure old data doesn't just crash their apps,
> but this prefix will remain as our main endpoint for this api going forward (aka once latest backup is restored)
=> Update TheGamesDB API URL to include "v1"

es-app/src/views/gamelist/DetailedGameListView.cpp, es-app/src/views/gamelist/DetailedGameListView.h, es-app/src/views/gamelist/VideoGameListView.cpp, es-app/src/views/gamelist/VideoGameListView.h
- Added support for md_thumbnail in VideoGameListView
- Added support for md_thumbnail & md_marquee in DetailedGameListView
=> Add support for md_thumbnail & md_marquee

es-core/src/components/VideoPlayerComponent.cpp
Should address #649 .
@tomaz82 - This seems to work correctly now on the Pi4, at least. I do recall us testing things out back in the day, so I'm not sure if it's something that changed between OS updates or just something that I missed back then.
Since it's OMXPlayer related, this would only apply on the Pi. If anyone can test this on a Pi3 prior to the latest Buster images, I'd appreciate it as I don't have one anymore. Otherwise, should be good to go.
=> Fix rotation for OMX Player

es-app/src/guis/GuiVideoScreensaverOptions.cpp, es-core/src/Settings.cpp, es-core/src/components/VideoPlayerComponent.cpp, es-core/src/components/VideoVlcComponent.cpp
- Added option to mute video screensaver audio for both VLC and OMXPlayer.
- Default should be "ON" as it has been so far.
- It should respect general audio settings.
=> Added option to disable video screensaver audio on VLC and OMXPlayer

es-app/src/guis/GuiMenu.cpp, es-app/src/views/ViewController.cpp, es-core/src/Settings.cpp
- Add option to show the small "Start Menu" version in Kids mode as well, for a locked down system with only the kids game on.
- Defaults to "OFF", to keep current behavior.
=> Option to show start menu in Kids mode

es-app/src/FileFilterIndex.h, es-app/src/MetaData.h, es-core/src/InputManager.h, es-core/src/Settings.h, es-core/src/Sound.h
Some files require to include the `<string>` header. The missing header prevents the compilation on GCC 10.1.0 . Probably with other compilers the header is implicitly included via other ones (maybe `<map>`). The proposed patch add the missing includes needed to compile without errors using GCC 10.
=> Fixed missing string includes needed by GCC 10

es-core/src/guis/GuiInputConfig.cpp
This message is usually only visible when configuring a button whose
configuration can be skipped. Set it correctly for the first button.
=> Input config: initialize hold any button to skip message visibility

es-core/src/resources/Font.cpp, es-core/src/resources/Font.h, es-core/src/resources/ResourceManager.cpp, es-core/src/resources/ResourceManager.h, es-core/src/resources/TextureDataManager.cpp, es-core/src/resources/TextureDataManager.h, es-core/src/resources/TextureResource.cpp, es-core/src/resources/TextureResource.h
The reloadable manager reloads every referenced textures even if they have been released to free vram.
This avoids to reloading still referenced textures that were already unloaded.
=> Fix Reloadables : Don't reload useless textures that were not loaded at unload time.

es-app/src/guis/GuiMenu.cpp
* Added 2 new mixer options - HDMI/Headphone - which should be used when the Pi's _snd_bcm2835_ module is configured with separate ALSA devices (see https://github.com/RetroPie/RetroPie-Setup/pull/3151). Seems to be the new default configuration in Buster now.
* Added the 'alsa' output option for 'omxplayer', which enables usage of the default ALSA output device.
* Removed the _HDMI_,_local_, _both_ sound cards options, they only make sense for OMXPlayer, the default ALSA card names for the Pi are not named like that.
=> Audio menu: adjust mixer and OMX sound output options

es-core/CMakeLists.txt, es-core/src/renderers/Renderer_GLES20.cpp
This still needs cmake scripts to choose between gles10 and gles20 depending on platform, and I simply have no idea how to do that black magic.
But this has been tested on both pi3b+ and pi4 with hardcoded cmake to force the gles20 renderer.
=> Adds a GLES20 renderer

es-core/src/guis/GuiInputConfig.cpp
Undo change to use std::array introduced by https://github.com/RetroPie/EmulationStation/pull/646
This broke compilation in both MSVC 2015 and 2017
=> Undo change to use std::array

es-app/src/PlatformId.cpp
`x68000` is the name of the ROMs folder and the platform name in RetroPie's `platforms.cfg`.
=> fix wrong Sharp X68000 platform id

CMake/Packages/FindOpenGLES.cmake, CMake/Packages/FindOpenGLES2.cmake, CMakeLists.txt, README.md
Added support for the GLESv2 renderer to the CMake build (added in https://github.com/RetroPie/EmulationStation/pull/642 by @tomaz82).
* Refactored the OpenGLES detection for both versions. Platform detection is done only in the main project file, settings hints (includes/libaries) for the GLES detection in the corresponding 'Find' cmake modules from `CMake/Packages`.
* Simplified the `FindGLES.cmake`, based on platform detection.
* Added building notes for the Raspberry Pi to _README.md_, the information from Aloshi's page is incomplete.
**Notes**:
* GLESv2 has been set as default for GLES-enabled systems.
* For the Raspberry Pi systems, both the legacy (BRCM) and the new (MESA) GLES libraries can be present (defaults to the legacy drivers). 
Selecting between them can be done via the …
=> cmake: add GLES20 renderer build support

es-core/src/Settings.cpp
New kernels now use HDMI / Headphone - see https://retropie.org.uk/forum/topic/26628/audio-issues-after-latest-raspbian-updates
=> changed RPI default AudioDevice to HDMI

es-app/src/PlatformId.cpp
Fixes scraping errors due to erroneous system chosen. Broken in https://github.com/RetroPie/EmulationStation/commit/a5f2739.
=> scraper: add missing 'daphne' platform index

es-core/src/ThemeData.cpp
Allows nested variables in themes
```
<variables>
<colorRed>8b0000</colorRed>
<themeColor>${colorRed}</themeColor>
<themeArtFolder>./art</themeArtFolder>
<themeFont>${themeArtFolder}/Cabin-Bold.ttf</themeFont>
</variables>
```
=> Nested variables in themes

THEMES.md, es-app/src/views/gamelist/DetailedGameListView.cpp, es-app/src/views/gamelist/GridGameListView.cpp, es-app/src/views/gamelist/VideoGameListView.cpp
More sane defaults for several components (md_image, md_video, md_marquee and md_thumbnail) and move the hidden ones offscreen and set their maxSize to entire screen
This fixes bugs in grid and video view where the image would get the wrong aspect ratio because the default maxSize was set to 1
Should fix issue https://github.com/RetroPie/EmulationStation/issues/667
=> More sane defaults for several components

es-core/src/components/VideoComponent.cpp
The behavior for this was inconsistent.
If the video had 0 delay, it would play even if video component was hidden (grid system didthis, you could hear the audio from the hidden video), but if it had a delay then it would not play at all because it was hidden.
The new behavior is that it won't play at all when hidden, delay or not.
Grid themes using this  broken behavior to get the audio to play can still get that by just setting the video component as visible but off screen (pr https://github.com/RetroPie/EmulationStation/pull/705 defaults it to offscreen), this also gives the ability to set a delay now so the grid system doesn't try to start every video as you scroll through the games.
=> Disable video playback if video component is hidden

es-app/src/components/TextListComponent.h
The +0.5 makes the math do a round, thus making the number of rows in the textlist one to many so it grows beyond the height of the component if the original fraction was .5 or bigger.
=> Fix textlist

es-core/src/components/GridTileComponent.cpp
This will break grid themes... padding and mBackgroundCornerSize was set in pixels rather than percentages, this is fixed now
=> Fix scale on padding and mBackgroundCornerSize in gridtile

THEMES.md, es-core/src/ThemeData.cpp, es-core/src/ThemeData.h
```
<theme>
<formatVersion>6</formatVersion>
<resolution>1920 1080</resolution>
```
This allows theme makers to use pixel values for most items in the theme instead of using percentages.
What ES will do then is take the pixel values and divide by the set resolution on load, so they end up being the percentages again in the end.
```
<image name="centerfade" extra="true">
<path>${themeArtFolder}/centerfade.png</path>
<size>1920 540</size>
<pos>960 540</pos>
<origin>0.5 0.5</origin>
<color>${themeColor}50</color>
</image>
```
versus
```
<image name="centerfade" extra="true">
<path>${themeArtFolder}/centerfade.png</path>
<size>1 0.5</size>
<pos>0.5 0.5</pos>
<origin>0.5 0.5</origin>
<color>${themeColor}50</color>
</image>
```
resolution defaults to 1 1 so this wont break existing themes.
This …
=> Adds a root <resolution> tag to themes

es-core/src/components/GridTileComponent.cpp
This hack fixes existing grid themes that will break from the fixes in https://github.com/RetroPie/EmulationStation/pull/710
=> Fix broken grid themes

es-app/src/views/gamelist/GridGameListView.cpp
Similar to https://github.com/RetroPie/EmulationStation/blob/7c346209dfc56af3685e9a309e2fa2e7b8d27650/es-app/src/views/gamelist/BasicGameListView.cpp#L66.
Prevents ES crashing when trying to update metadata on a placeholder value, like the 1st entry on an empty custom collection.
=> gridview: ignore placeholders on metadata updates

CMakeLists.txt
Changed the CMP0072[1] `cmake` policy to use `libGL` for OPENGL_LIBRARIES,
instead of `libOpenGL`, provided by `libglvnd` (default from `cmake` 3.11).
This should fix situations where there the OpenGL implementation doesn't have
`glvnd` support and `emulationstation` gets linked to the `glvnd` library.`libSDL2`
dl-loads a different `libGL` and this results in a non-working GL context.
[1] https://cmake.org/cmake/help/git-stage/policy/CMP0072.html
Should fix #727 and probably other issues reported in the forums with recent Ubuntu (20.x) that have a new `cmake` version.
=> cmake: use the non-glvnd version of GL libraries

es-app/src/guis/GuiVideoScreensaverOptions.cpp, es-core/src/Settings.cpp, es-core/src/components/VideoVlcComponent.cpp
Removed explicit exclusion of VLC resolution options from the Pi, as the Pi4 can now handled it well, and is the only option on the Pi4 for subtitles given that OMX Player doesn't play subtitles on the Pi4 and crashes: https://github.com/popcornmix/omxplayer/issues/736
Also changed the resolution options to allow for more flexibility in upscaling other than "original video resolution" and "full screen resolution" as it can be taxing on lower-end devices.
Also made explicit that some options only apply to OMX Player and others (one) only to VLC, as I had left it a bit ambiguous back in the day.
=> Update video screensaver settings

es-app/src/Gamelist.cpp
This PR improves the Gamelist Update logic on save in a few ways:
- Iteration logic: instead of iterating the entire XML for the system (larger data set) for each changed game (smaller data set), it iterates the entire XML only once (or twice, if folders can get updated somehow as well? I kept that logic though I'm not sure if it ever runs);
- Less expensive transformations: instead of relying on a path transformation that stats the file path every time - for each entry in the gamelist and then for the path in the in-memory FileData - we now just apply the same transformation we use when loading the path to the FileData structure in memory which is less expensive and we're effectively just using them to match whether that FileData corresponds to that XML element. This makes it more …
=> Improve Update Gamelist logic and performance

es-app/src/views/gamelist/VideoGameListView.cpp, es-core/src/components/VideoComponent.cpp, es-core/src/utils/FileSystemUtil.cpp
This change improves file-system accesses, especially on remote systems. 
Currently there are multiple instances of unnecessary file-system accesses for checking if files exist, including consecutively when updating the UI and loading the assets for each game during navigation.
This implements a quick and dirty index map for such "exists" operations that are somewhat expensive in remote storage scenarios (NAS), averaging 100ms each, causing navigation to be unnecessarily slow.
Also, changed some of the file-system accesses and calculations on the video player front.
If useful I can implement this as an option, but didn't want to over-engineer it. I suppose the only reason that this would not be desired is if the actual files that ES expects to point to actually change in runtime, outside …
=> Improve file-system accesses

es-app/src/CollectionSystemManager.h, es-app/src/SystemScreenSaver.cpp, es-app/src/SystemScreenSaver.h, es-app/src/guis/GuiMenu.cpp, es-core/src/Settings.cpp
Depends on #688 - it includes that commit here, so don't review this beforehand. 
This PR adds an option to run a background job during the screensaver to index files/resources that will be used by ES, to reduce expensive file-system operations during runtime, especially on network media.
It indexes game images, thumbnails, marquees and videos which are, to the best of my understanding, all the external resources that are accessed in runtime when navigating and that can benefit from being cached.
=> Adds option for background resource indexing during screensaver

es-app/src/VolumeControl.cpp
Only this file, errorlog message contains Class::Function name. 
...and it looks inappropriate.
=> Fix insignificant message typo in VolumeControl.cpp

es-app/src/FileSorts.cpp, es-app/src/FileSorts.h, es-app/src/guis/GuiGamelistOptions.cpp, es-app/src/guis/GuiMenu.cpp, es-app/src/guis/GuiMenu.h, es-core/src/Settings.cpp
This enhancement replaces #726 by adding an option called `Ignore Articles (Name Sort Only)` to the START menu.  When enabled, common leading articles are ignored in both ascending and descending order while sorting each system's game titles, similar to popular multimedia-based systems.  The comma-delimited list of articles is stored within the `es_settings.cfg` file as `LeadingArticles`.  By default, common English articles "a", "an", and "the" are ignored, and others may be added to the list manually.  (This also allows more articles to be easily added to the default setting going forward.)  The option itself is persisted as `IgnoreLeadingArticles`.
~~Additionally, all file sorting options are consolidated into one application-wide location by moving the `Sort Games By` selection from …
=> Add option to ignore common leading articles in Filename sort

es-app/src/components/TextListComponent.h
In \<textlist\>, setUppercase() always set mUppercase to true.
other elements are work correct.
=> Allow <forceUppercase>0</forceUppercase> in <textlist>

es-app/src/components/TextListComponent.h
Fixes the textlength calculation  which is used to detect the scrolling (x-axis) of a long game name in the gamelist view.
This fix honors the uppercase flag if used by a theme to display game names in the gamelist view (e.g. in Carbon theme).
Refers to: https://retropie.org.uk/forum/topic/30133/scroll-of-title-of-game-better-understand-how-it-works
=> Fixes scroll detection for themes with forceuppercase gamelist display

es-app/src/CollectionSystemManager.cpp, es-app/src/CollectionSystemManager.h, es-app/src/guis/GuiCollectionSystemsOptions.cpp, es-app/src/guis/GuiCollectionSystemsOptions.h, es-app/src/guis/GuiInfoPopup.cpp, es-app/src/guis/GuiInfoPopup.h, es-app/src/views/gamelist/ISimpleGameListView.cpp, es-app/src/views/gamelist/ISimpleGameListView.h, es-core/src/Settings.cpp
Adds a option which hinders accidentally removal of a game from Favorites or the Collection currently edited.
When enabled a toast / popup is shown to press again to confirm remove (within 1.5sec).
Default is disabled (Option in UI Settings: 'Press (y) twice to remove from favs./coll.'): Removes a favorite when Y is pressed once on a game marked as favorite (as-is implementation).
Refers to:  #326
=> Remove from favorites/collections with double press of Y button

es-app/src/components/TextListComponent.h, es-app/src/guis/GuiMenu.cpp, es-core/src/Settings.cpp
Configurable option to allow full page up down with lb/rb.
Default is off ("use full screen paging for lb/rb" in UI Settings), which is the current implementation: -10/+10 per lb/rb press.
Refers to: 
https://retropie.org.uk/forum/topic/29459/page-up-down-function-on-es-textlists-via-lb-rb-not-accurate
=> Full screen paging in gamelist view with lb/rb

es-app/src/PlatformId.cpp
Scraping does not work with pokemon mini
This is because the default name for the platform when installing `lr-pokemini` is `pokemini` and not `pokemonmini`
```
<system>
<name>pokemini</name>
<fullname>Pokemon Mini</fullname>
<path>/home/pi/RetroPie/roms/pokemini</path>
<extension>.min .zip .MIN .ZIP</extension>
<command>/opt/retropie/supplementary/runcommand/runcommand.sh 0 _SYS_ pokemini %ROM%</command>
<platform>pokemini</platform>
<theme>pokemini</theme>
</system>
```
=> fix pokemon mini default platform name

es-core/src/resources/TextureData.cpp
SVGs were getting cropped at the right side based on certain conditions. This was due to the scaling when rasterizing an image only being based on the height.
Before:
After:
=> Fix issue with svg scaling

es-core/src/resources/ResourceManager.cpp
tellg can report -1 if there was an error while reading the file, and because it was casted to a size_t type which is unsigned, this will become 18446744073709551615. It will then attempt to allocate that many bytes and of course crash! This will just return an empty resource if there was an error.
=> handle error while reading file

es-app/src/main.cpp
Use a different approach for discarding any queued input events during startup.
We want to make sure that when the UI is shown, there are no pending events that could
start a game/open the menu/switch system/etc.
The new code allows also to:
* ignore input events during splashscreen
* handle the case when a keyboard/keyboard type controller is used
* allow the handling of SDL_JOYDEVICEADDED events (which were discarded with `SDL_JoystickEventState(SDL_DISABLE)`
=> input: change how input events during start are discarded

es-app/src/SystemData.cpp, es-app/src/SystemData.h, es-app/src/SystemScreenSaver.cpp, es-app/src/SystemScreenSaver.h, es-app/src/main.cpp, es-core/src/Window.cpp, es-core/src/Window.h, external/CMakeLists.txt
Used in _Random_ (X-Button function) and in screensaver random screenshots, videos, custom images.
- Use of uniform RNG (PCG) with more random seeding than time(NULL)
- Shuffles systems (aso.) like a card deck and picks top system until empty, then shuffles again
- Different shuffle on every ES start and every re-shuffle
- Fixes the flaws of the current random implementation: Real 1/N chance for an element in a set of N
- Minor refactorings
Relates to findings stated here: https://retropie.org.uk/forum/post/261120
Tested entirely on a Rpi4.
Looks large but on ES side it is mainly SystemData and SystemScreenSaver the larger part is [PCG source tree](https://www.pcg-random.org/).
=> Better Random: Perfect shuffle of systems, games and screensaver items

es-core/src/InputManager.cpp
This ensures that configurations created before HIDAPI drivers were enabled by default (2.0.12)
will work when EmulationStation uses a newer SDL2 version.
Using the HIDAPI drivers may produce a different name for joysticks and pottentially changes the mapping.
Example using a PS4 (Dualshock 4) controller:
- without HIDAPI, the controller is named "Wireless Controller", with HIDAPI enabled is named "PS4 Controller"
- without HIDAPI, the D-Pad is detected as a HAT, but with the drivers enabled it's detected as a series of buttons
- the device GUID is different between the 2 configurations
The different name would probably break also the input configuration script for RetroArch, which doesn't use SDL2 as default input driver and would receive a wrong name and wrong mappings.
Note that the …
=> input: disable the SDL2 HIDAPI drivers by default

es-core/src/utils/FileSystemUtil.cpp
Allow for multilevel absolute paths in gamelist.xml.
See discussion here: https://retropie.org.uk/forum/topic/30984/multi-level-absolute-paths-in-gamelist-xml-not-working?_=1631445878380
=> Update FileSystemUtil.cpp - Allow for multilevel absolute paths in gamelist.xml

es-app/src/PlatformId.cpp, es-app/src/PlatformId.h, es-app/src/scrapers/GamesDBJSONScraper.cpp, es-app/src/scrapers/ScreenScraper.cpp
Added:
* Nintendo Switch (TGDB, ScreenScraper)
* TIC 80 (ScreenScraper)
* PICO-8 (ScreenScraper)
* Sam Coupe (TGDB, ScreenScraper)
* PC-FX (TGDB, ScreenScraper)
* ZMachine (ScreenScraper)
Updated:
* ZX81 Sinclair (added scraping for TGDB)
=> Scraping platforms update

es-app/src/SystemScreenSaver.cpp, es-app/src/SystemScreenSaver.h, es-app/src/guis/GuiSlideshowScreensaverOptions.cpp, es-core/src/PowerSaver.cpp, es-core/src/Settings.cpp, es-core/src/Settings.h, es-core/src/Window.cpp
Adds support for .mp4 and .avi video files in the custom image directory with the screensaver Slideshow mode. Also adds those extensions to the default settings.
Inspired by [https://retropie.org.uk/forum/topic/12733/animated-screensavers](https://retropie.org.uk/forum/topic/12733/animated-screensavers)
Allows a user to have animated screensavers AND game preview videos at the same time.
Tested on Raspberry Pi 4.
This is my first time working in C++ or attempting to contribute to an open source project, constructive criticism is appreciated. I tried to add this feature while changing as little as possible, my biggest problem was that Slideshow is only associated with images, while Random Video is only associated with game nodes. This makes some things a bit confusing, such as adding …
=> Feature: Slideshow screensaver video support

THEMES.md, es-core/src/utils/TimeUtil.cpp
The change extends the DateTime formatting options and simplifies a bit the code.
The `strftime` format is compatible with the format specifiers that are used right now, so it shouldn't cause any incompatibilities with themes.
=> TimeUtil: use `strftime` for date/time formatting.

es-core/src/Scripting.cpp, es-core/src/utils/FileSystemUtil.cpp
Refers to: https://retropie.org.uk/forum/topic/29651/emulation-station-game-start-script-not-executable
=> Improved warning message when userscript is not mode 755.

es-core/src/resources/Font.cpp, es-core/src/resources/Font.h
This is a re-work of PR#269 and PR#314:
* originally proposed by @eagle0wl and discussed/tested with @zigurana during #269, with the motivation being to accomodate texts in languages that don't use spaces between successive characters and words (e.g. Japanese/Chinese).
* @zigurana created a smaller PR in #314 (now closed), but hasn't been updated after @tomaz82's work that changed the Unicode (UTF8) string handling functions (see #297).
I've taken the changes from @zigurana's PR (#269) and updated the code to use `Utils::String::chars2Unicode`.
I added a smaller change for parsing the text. Since we analyze each Unicode code point now (instead of a string), I replaced the `sizeText` call with a simpler function, which gets the size for just the codepoint being scanned. `lineWidth` is …
=> Improve text wrapping (rebased #269)

es-app/src/guis/GuiFastSelect.cpp, es-app/src/views/gamelist/ISimpleGameListView.cpp
Fixes #775 . 
Tested here: https://retropie.org.uk/forum/topic/32086/es-dev-bug-report-hidden-filter-fails-at-system-level-after-entering-a-subfolder-and-returning
=> Fix navigating to parent when list is filtered

es-core/src/resources/Font.cpp
Don't wrap at all if maxWidth is 0 or negative
=> Fix infinite loop in wrapText when maxWidth is less than 0

es-app/src/scrapers/ScreenScraper.cpp
Fixed the ScreenScraper search by user input, since it only by searched by filename and ignored the user input for the game name.
=> scraper: teach ScreenScraper to use the user input

es-app/src/FileData.cpp, es-app/src/SystemScreenSaver.cpp, es-app/src/views/SystemView.cpp, es-app/src/views/ViewController.cpp, es-app/src/views/gamelist/ISimpleGameListView.cpp, es-core/src/Scripting.cpp, es-core/src/Scripting.h, es-core/src/Window.cpp
Hi modified the core Scripting.h and Scripting.cpp at add an additional optional parameter to support triggering events and running script files that take "system name", "rom file name", "rom file game name" as parameters to their command-line.  I also modified the necessary files to trigger events for when the game selected via the UI changes, the system selected via the UI changes, or the screen saver switches videos or shows no video at all.  The changes allow easier interception of those events that I originally did to integrate the PixelCade LED Marquee with ES without having to use a custom build of ES to support it.  The logic that was modified I have moved and enhanced into the bash scripts that now get executed so developers can customize the behavior to their own liking.
For …
=> Changes necessary to implement Scripting events for "game-select", "system-select" and "screeensaver-game-select"

README.md, es-app/src/main.cpp, es-app/src/views/ViewController.cpp, es-core/src/Settings.cpp
This PR relates to my comment a while ago:
https://github.com/RetroPie/EmulationStation/pull/722#issuecomment-776106939
Additionally, I removed the internal `SplashScreenProgress` switch as it is always true. I assume it is an appendix leftover from development.
However, I deliberatly did not squish so you may decide what to accept.
PS: Did close the previous PR with same topic by accident.
=>  Brooming of --help output

es-core/src/components/VideoPlayerComponent.cpp
https://retropie.org.uk/forum/topic/32586/emulationstation-freezes-after-game-select-event-triggered-and-video-snap-plays
This fixes a race condition between the Video component's `SIGCHLD` signal handler and `system()` calls via Scripting events that causes EmulationStation to become unresponsive.
I was exploring the use of the new `game-select` event introduced in https://github.com/RetroPie/EmulationStation/pull/751 and found that EmulationStation was becoming unresponsive to new inputs (e.g. up / down) when the OMX player was enabled and a `game-select` script was added.
I was able to confirm:
* The issue goes away when the OMX player is disabled
* The issue goes away when the `game-select` script is removed
* The issue remains with the latest `master` branch of EmulationStation
* The …
=> Fix race condition between Video component and Scripting events causing ES to freeze

CMakeLists.txt, README.md, es-app/src/SystemScreenSaver.cpp, es-app/src/guis/GuiMenu.cpp, es-app/src/guis/GuiVideoScreensaverOptions.cpp, es-app/src/views/gamelist/GridGameListView.cpp, es-app/src/views/gamelist/VideoGameListView.cpp, es-core/src/Settings.cpp, es-core/src/components/VideoPlayerComponent.cpp, es-core/src/components/VideoPlayerComponent.h
Modified the build options and source files to enable `omxplayer` for video previews only when the `OMX` option is used.
Updated the build instructions on RPI accordingly and added some notes about the deprecation of the BRCM GPU drivers in RasPI OS 'Bullseye'.
Previously, the `RPI` build option would be used to add both RPI specific audio settings/VRAM limits AND add `omxplayer` support. However, `omxplayer` does not work with the RPI KMS video driver (`vc4-kms-v3d`) or with a 64bit RPI system, due to the lack of OpenMAX (OMX) API support.
The new RasPi OS ('bullseye') has made the KMS driver the default [1] and doesn't offer `omxplayer` anymore (considered deprecated [2]).
Splitting the OMX support from the RPI option allows to set some default values for RPI systems without …
=> RPI support: split omxplayer build option

CMakeLists.txt
Add option USE_GL21 to enable OpenGL 2.1 renderer which can be activated with „-DUSE_GL21=On“. Use
OpenGL 1.4 by default for backward compatibility.
=> renderer: Add build option for OpenGL 2.1

es-core/src/utils/FileSystemUtil.cpp
With this fix in place, emulationstation will start up correctly when there is no ~/.emulationstation directory present.
=> FileSystemUtil: Update path cache when creating new directory

es-core/src/utils/TimeUtil.h
Included `time.h` to get the declarations of `time_t` and `struct tm`.
Should fix building with `gcc` 12.x.
Should fix #804.
=> timeutil: fix building with recent `gcc` versions.

es-app/src/FileData.cpp, es-app/src/main.cpp, es-core/src/InputManager.cpp, es-core/src/Window.cpp
This happens whenever a joystick is remved during ES splashscreen. Putting the PR here after initial discussion in forum:
https://retropie.org.uk/forum/topic/33014/failed-assertion-on-connected-joysticks-terminates-emulationstation-on-specific-conditions
=> Fixes ES crash after boot on stale SDL joy add/remove events.

es-app/src/CollectionSystemManager.cpp, es-app/src/guis/GuiGamelistOptions.cpp, es-app/src/views/gamelist/BasicGameListView.cpp, es-app/src/views/gamelist/BasicGameListView.h, es-app/src/views/gamelist/GridGameListView.cpp, es-app/src/views/gamelist/GridGameListView.h, es-app/src/views/gamelist/IGameListView.h
Added an extra parameter for the `remove` call, hinting that a refresh of the View is not desired.
This skips any `onFileChanged` event called at the end of `remove`, leaving it to the caller to explicitely call the `onFileChanged` method. The skip decreases the time spent in `remove`.
The sole usage - right now - is during the initial built-in collections creation, when the `recent` collection trimming can take a long time when it has >>50 entries.
=> ViewController: improves bulk removal of entries

es-app/src/CollectionSystemManager.cpp
This could happen if no mCustomCollectionsBundle was initialized.
=> CollectionSystemManager: Fix possible crash in destructor

es-core/src/resources/TextureData.cpp
It should be noted that nsvgDelete(NULL) [is safe](https://github.com/RetroPie/EmulationStation/blob/master/external/nanosvg/nanosvg.h#L2962).
On my very limited set-up, >400 KiB of memory was freed up.
=> TextureData: Fix memory leak of svgImage

es-core/src/InputManager.cpp
The `<inputAction>` node is useless for the temporary input configuration, so remove it.
Normally, because of the previous `reset` call of the parent document, it would be empty, but I've encountered situations when the memory is not cleared and there's (random binary) garbage added to the temporary configuration file. This results in a broken XML file and the auto-configuration scripts in RetroPie will all fail.
=> input: remove useless XML node in the temporary output

es-core/src/components/TextComponent.cpp, es-core/src/resources/Font.cpp
The ellipsis effect instead of wrapping to a new line had two causes:
1. A short description ends slightly after the x-bounding value of the textcomponent (can happen in any theme).
2. Themes with a linespacing with less than 1.2 (120% of highest character) get a wrong flag set for detecting if it is a multi line text. Carbon uses 1.5 linespacing by default thus this case never to carbon.
Fixes:
1. An additional clause in Font.cpp::wrapText() was added to fix this effect and to force wrapping instead of adding ellipsis.
2. The evaluation of the variable isMultiline in TextComponent::onTextChanged() takes the actual linespacing for calculation instead of the "magic float" of 1.2.
Resolves #796.
cf. https://retropie.org.uk/forum/topic/32893/very-short-descriptions-don-t-wrap
=> Make short descriptions wrap to next line instead of adding ellipsis.

es-app/src/components/TextListComponent.h, es-app/src/views/ViewController.cpp, es-app/src/views/gamelist/BasicGameListView.cpp, es-app/src/views/gamelist/BasicGameListView.h, es-app/src/views/gamelist/GridGameListView.h, es-app/src/views/gamelist/IGameListView.h, es-app/src/views/gamelist/ISimpleGameListView.h, es-core/src/components/IList.h
As tabled in the forum
https://retropie.org.uk/forum/topic/33200/full-page-scrolling-misplaces-cursor-at-some-conditions
Also fixes #798
=> Fix misplaced cursor on LB/LR paging on specific conditions

es-core/src/components/TextComponent.cpp, es-core/src/components/TextComponent.h
This is a optimization followup to PR #803.
Main changes are to call `calculateExtent();` only when text is present and keep the text once rendered/calculated for screen size instead of recalculating it everytime.
It is a refactoring to optimize the runtime/call count of `TextComponent.onTextChanged()`
I ran the `ProfilingUtil` on the method before...
```
Aug 17 14:45:45 lvl3: 	Message                     	       Calls	  Total Time	    Avg Time	    Min Time	    Max Time	 Internal Total Time	   Internal Avg Time
Aug 17 14:45:45 lvl3: 	TextComponent::onTextChanged	        6328	    1.594224	    0.000252	    0.000000	    0.027193	            1.594224	            0.000252
```
...and after (~60% less calls and ~15% faster per call):
```
Aug 18 23:16:25 lvl3: 	Message …
```
=> Reduces callcount to TextComponent.onTextChanged()

es-core/src/InputConfig.cpp, es-core/src/InputConfig.h, es-core/src/InputManager.cpp
Added some extra info to help RetroPie's auto-configuration scripts by exporting the joystick Vendor and Product IDs, which should help with RetroArch's joypad profile generation.
Since 2.0.14, SDL's joystick name (`SDL_CreateJoystickName`) is a normalized version of the name reported by the OS (culled consecutive spaces, trimming trailing spaces, renaming known joystick names like Xbox/PS). This breaks the input auto-configuration scripts in RetroPie, which generate a config with new name, while the emulators/ports expect to find the OS reported name (e.g. RetroArch - see #3398 [1] for an example).
This issue is affecting especially PC users, which are not using RetroPie's (old) SDL version and who's RetroArch configuration is incomplete.
Using the Vendor/Product ID would help these …
=> input: export additional info for joysticks inputs

.github/workflows/ccpp.yml, .github/workflows/win32.yml, CMake/Packages/FindRapidJSON.cmake, CMake/Utils/FindPkgMacros.cmake, CMakeLists.txt, README.md, es-core/src/components/VideoVlcComponent.cpp
This **pull request** (PR) provides the ability to build a **WIN32** version of _RetroPie's_ **EmulationStation**. This PR contains a minimal number of code changes as to not impact building **EmulationStation** for the various **Linux** distros. Detailed documentation for building **EmulationStation** for **Windows** was added to the **README.MD** file (preview [HERE](https://github.com/WiltonMicroSystems/EmulationStation/blob/WIN32/README.md)). In addition, a **GitHub Action** was added to automate the **WIN32** build process using a _free_ **Windows 2022** runner containing the current generation of tooling (e.g., **Visual Studio 2022**).
A compiled **WIN32** build from this PR can be downloaded from [HERE](https://github.com/WiltonMicroSystems/EmulationStation/releases/tag/v2.12.0-win3 …
=> Add and document WIN32 build support

es-app/src/views/gamelist/GridGameListView.h
This pull request addresses 2 compiler warnings related to overrides.
```
In file included from /home/devel/git/EmulationStation/es-app/src/views/gamelist/GridGameListView.cpp:1:
/home/devel/git/EmulationStation/es-app/src/views/gamelist/GridGameListView.h:24:15: warning: 'setViewportTop' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
virtual void setViewportTop(int index) { ; }
^
/home/devel/git/EmulationStation/es-app/src/views/gamelist/ISimpleGameListView.h:28:15: note: overridden virtual function is here
virtual void setViewportTop(int index) override = 0;
^
In file included from /home/devel/git/EmulationStation/es-app/src/views/gamelist/GridGameListView.cpp:1:
/home/devel/git/EmulationStation/es-app/src/views/gamelist/GridGameListView.h:25:1 …
```
=> Resolved compiler warnings using clang 14.0.0 on Ubuntu-22.04.3

README.md
LibVLC version 3 is required starting with #824.
=> docs: document the libVLC dependency

es-app/src/guis/GuiGamelistOptions.cpp
The null selection will then on confirming "Jump to ..." in the Gamelist Options menu crash ES (assertion failed in https://github.com/RetroPie/EmulationStation/blob/44df564dcfa30dc07781edb90491b3d2acb85e1c/es-core/src/components/OptionListComponent.h#L238)
How to reproduce:
1. Rename a Rom filename or when using a gamelist name a rom via <name> or <sortname> and use as first character either a whitespace, a tilde, or an Umlaut/8-Bit ASCII value or similar (I stumbled across this bug with the name Ō in Ōkamiden).
2. Restart ES or reload gamelist
3. Navigate to the just renamed ROM and highlight it with the cursor
4. Press _Select_ to open "Gamelist Options Menu"
5. Notice the null selection (only the arrows are displayed in "Jump to ..."
6. Confirm the null selection in  "Jump to ..." …
=> Fixes the null selection for ROMs starting with Unicode or Umlauts

es-core/src/components/VideoVlcComponent.cpp
Recent update for Ubuntu added the unistd.h include which is not available in at least VC2017 nor 2019.
=> Fix VC2017 not having unistd.h

es-app/src/CollectionSystemManager.cpp, es-app/src/FileData.cpp, es-app/src/FileData.h, es-app/src/FileSorts.cpp, es-app/src/guis/GuiGamelistOptions.cpp, es-app/src/guis/GuiGamelistOptions.h, es-app/src/guis/GuiMetaDataEd.cpp
- Sort order not remembered during ES session
- "Jump to ..." only correct on "name, asc." sort order
- Metadata edit with rename name leaves list cursor misplaced
- Scroll of long filename in gamelist restarts even if option dialog is closed without any changes
- Sort order description "filename" changed to "name"
- Some minor code smells
=> Fixes these glitches in UI gamelist options menu:

es-app/src/CollectionSystemManager.cpp, es-app/src/Gamelist.cpp, es-app/src/MetaData.cpp, es-app/src/SystemData.h, es-app/src/scrapers/GamesDBJSONScraper.cpp, es-app/src/scrapers/ScreenScraper.cpp, es-core/src/InputConfig.cpp, es-core/src/InputManager.cpp, es-core/src/MameNames.cpp, es-core/src/Settings.cpp, es-core/src/ThemeData.cpp, external/CMakeLists.txt
This PR corrects the pugixml include paths to the paths that pugixml is ought to be included from when installed as a package.
These also work when pugixml is built locally from source.
In addition to that, i added a conditional that builds pugixml from source if it is not available as a system-wide installation.
=> Fix pugixml include paths and make submodule optional

es-app/src/Gamelist.cpp
Updated the parsing of an existing gamelist to exclude entries without an extension present in `es_systems.cfg`. 
This can happen when the list of extensions is updated and some extensions are removed, but the `gamelist.xml` entries are not removed. EmulationStation would still consider the excluded extension's entries as valid gamelist entries, without filtering them out.
Some perf. testing done with _ProfilingUtil_ doesn't show a meaningful impact over the previous code.
=> Gamelist bugfix: don't show un-registered extensions

es-app/src/SystemData.cpp
This reverts the changes in 5349be1dcebd35c0f9d5698b0508caeba61ed1a5 that lower-cased the extension of the files listed and the system registered extensions.
On case-sensitive filesystems (i.e. Linux), this restores the ability to 'hide' certain files from being shown just be changing the case of the files' extension. This ability is used by certain RetroPie users to hide unwanted files, without them showin up in the gamelist, by modifying `es_systems.cfg` and removing the uppercase extension of the files.
=> system: don't lowercase the extensions during parsing

es-core/src/Window.cpp
Fixes a bug that causes a game to launch when either _Start_ or _A_ is pressed when ES in in sleep mode.
In essence it is the check for `mSleeping`, the rest is refactorings.
I tested it to have no refressions.
=> fix 'input in sleep mode starts game'

es-app/src/CollectionSystemManager.cpp, es-app/src/SystemData.cpp, es-app/src/SystemData.h
The last random method updates from 2021 could keep in memory a vector of pointers to objects that had since been removed, causing a crash when updating the collection metadata. Reported in the forums as well.
=> Fix crash during collection updates

es-app/src/SystemScreenSaver.cpp
The recent fix to launching a game from the screensaver for OMXPlayer could now cause a crash on VLC because of multi-threaded execution, where depending on the execution order we could try to join the thread process where it would no longer exist. This should fix it.
=> Fix crash on game launch from screensaver

es-core/src/Window.cpp
Some controllers send ghost inputs at times (slight analog movements, or others) that would wake up the video screensaver when expecting other controls. This change ignores any unmapped input in that context (video/image screensaver, and screensaver controls ON).
I didn't expand it to other screensaver modes as I don't know how widespread or annoying ghost inputs are on other setups, and didn't want to break potentially expected behaviors (i.e. pressing any key whatsoever to wake up from screensaver, even if it's not mapped in EmulationStation).
=> Ignore unmapped windows during screensaver controls

es-core/src/Log.cpp
When ES is unable to open the logfile (for instance when the filesystem is readonly), it segfaults on closing because ES doesn't check if the file is open.
=> Fix logfile closing when logfile is not opened

es-app/src/components/RatingComponent.cpp
Change order so we render the filled texture top of the filled texture. This showed up in themes where the ratings image had been customized.
=> Fix rendering of opaque rating textures

es-app/src/views/ViewController.cpp, es-app/src/views/ViewController.h, es-app/src/views/gamelist/BasicGameListView.cpp
Add logic to only recreate view if automatic, or in a view type that can be upgraded with metadata details.
I'd love a second opinion on this.
=> Only recreate GameList View if it can change type

es-app/src/CollectionSystemManager.cpp, es-app/src/CollectionSystemManager.h, es-app/src/SystemScreenSaver.cpp, es-app/src/SystemScreenSaver.h, es-app/src/guis/GuiGamelistOptions.cpp, es-app/src/guis/GuiGamelistOptions.h, es-app/src/views/gamelist/ISimpleGameListView.cpp, es-app/src/views/gamelist/ISimpleGameListView.h, es-core/src/Window.cpp, es-core/src/Window.h
Added functionality:
- Launch random screensaver from within a system, limiting the media to that system
- Add "back" and "favourites" control to screensaver, to play the previous video, and/or to add video to favourites (or currently selected collection, as if one had pressed the favourites button in the gamelist).
Changes:
- Refactored some code, namely moving the input handling code for the screensaver from the Window class to the actual SystemScreenSaver class, and auxiliary code that was there as well;
- Adjusted code for the random screensaver not to pick a new random game (for the case when you're going back, you want to feed it a game to load);
- Added option to Select menu to launch screensaver, when applicable.
=> Improve random video/image screensaver controls

es-app/src/views/gamelist/BasicGameListView.cpp
This reverts part of commit beb193ce0a1f00dbfcc011ed49dcb1f3c27b98b2 for unintended behaviors. The attempt at optimizing performance broke other simple navigation cases, which means this needs more thorough investigation.
=> Revert "Only recreate GameList View if it can change type"

es-app/src/CollectionSystemManager.cpp
Attempt to reduce the time it takes to add/remove a game to/from a collection by 80%-90%.
Heavily commented the change for future reference.
=> Try to improve performance when adding/removing games from collections

es-app/src/CollectionSystemManager.cpp, es-app/src/CollectionSystemManager.h, es-app/src/SystemScreenSaver.cpp, es-app/src/SystemScreenSaver.h, es-app/src/guis/GuiCollectionSystemsOptions.cpp, es-app/src/guis/GuiCollectionSystemsOptions.h, es-core/src/Settings.cpp
- Add option in Game Collections menu to specify default collection to store games during screensaver
- Minor refactorings of the menu code
- Strengthening collections and menu code against edge cases from manual intervention in config files leading to crashes due to invalid values in these settings
=> Add option to specify collection to store favorites from screensaver

es-core/src/components/VideoVlcComponent.cpp
The VLC video player would not update its audio state after initialization, so if the user would change the audio preferences in settings this would fail.
=> Fix VLC not unmuting itself after initialization

README.md
Correcting my previous updates to "README.md" on building for WIN32. More specifically, removing the double quotes when setting the environment variables for CMAKE. The double quotes can break the ability for CMAKE to find the required packages. This change also matches the corresponding GitHub Action ([win32.yml](https://github.com/RetroPie/EmulationStation/blob/master/.github/workflows/win32.yml)) which correctly does not include the double quotes.
=> Small corrections to WIN32 build documentation in README.md

es-app/CMakeLists.txt, es-app/src/CollectionSystemManager.cpp, es-app/src/CollectionSystemManager.h, es-app/src/guis/GuiCollectionSystemsOptions.cpp, es-app/src/guis/GuiCollectionSystemsOptions.h, es-app/src/guis/GuiGamelistOptions.cpp, es-app/src/guis/GuiGamelistOptions.h, es-app/src/guis/GuiRandomCollectionOptions.cpp, es-app/src/guis/GuiRandomCollectionOptions.h, es-core/src/Settings.cpp
- Add an automatic Random collection.
- Menu allows user to select which systems to use as source, how many games from each system, and a maximum size for the collection, should they choose to.
- This requires changes to the themes, if users enable it.
=> Add support for a Random collection

es-app/src/Gamelist.cpp, es-app/src/MetaData.cpp, es-app/src/MetaData.h, es-app/src/guis/GuiGamelistOptions.cpp, es-app/src/guis/GuiMetaDataEd.cpp, es-app/src/guis/GuiMetaDataEd.h, es-core/src/components/DateTimeComponent.cpp, es-core/src/components/DateTimeComponent.h, es-core/src/components/DateTimeEditComponent.cpp, es-core/src/utils/TimeUtil.h
1. folder elements are loaded when present in a gamelist and if they match the filesystem representation
2. missing optional folder elements are rendered empty in theme (and not "unknown")
3. As before non-existing folder elements are generated by ES, with mandatory elements `<path/>` and `<name/>`, but with this PR, whenever metadata is edited for this folder object (FileData class) it is persisted
4. Editiing metadata on existing `<folder/>` gets persisted too
5. UI metadata edit: layout fix that renders entered metadata not centered when returning from editing
6. UI metadata edit: format tooltip for date format in release date field
=> Changes to maintain and persist <folder/> information in a gamelist:

es-app/src/SystemScreenSaver.cpp
The latest screensaver updates were causing a harmless warning for setting an empty collection to edit.
Fixing the cause that led to the warning.
=> Address warning when exiting screensaver

es-core/src/HttpReq.cpp
Starting with 7.85, `CURLOPT_REDIR_PROTOCOLS` is deprecated [1] and `CURL_REDIR_PROTOCOLS_STR` [2] should be used instead. The changes modify the option used depending on the (compile time) libcurl version.
[1] https://curl.se/libcurl/c/CURLOPT_REDIR_PROTOCOLS.html
[2] https://curl.se/libcurl/c/CURLOPT_REDIR_PROTOCOLS_STR.html
This is a proper fix instead of https://github.com/RetroPie/EmulationStation/pull/836.
Closed #836.
=> Handle cURL library deprecation for redirect options

es-app/src/CollectionSystemManager.cpp, es-app/src/CollectionSystemManager.h, es-app/src/guis/GuiCollectionSystemsOptions.cpp
Fixes the bug in this scenario:
1. Select in _Main Menu_ -> _Game Collection Settings_ -> _Create New Custom Collection from Theme_ or _Create New Custom Collection_
2. Notice the toast which states that you are editing the custom collection now
3. Add at least one game with _Y_-Button to the collection
4. Select in _Main Menu_ -> _Game Collection Settings_ -> _Finish Editing 'xyz' Collection_
2. Notice the toast which states editing has ended
5. Quit EmulationStation via the _Main Menu_ (do not use _F4_) 
6. Restart EmulationStation
**Result**
The custom 'xyz' collection is not created, or if it was a theme based custom collection it is no longer present on the carousel.
**Expected result**
After restart/reboot, the new collection is still available/present in ES and contains the games …
=> Fix persistence of new collections, either from theme or custom name

es-app/src/main.cpp
`--fullscreen-borderless`
There is no explanation for only this option.
=> help text for option --fullscreen-borderless

es-app/src/main.cpp, es-core/src/Settings.cpp, es-core/src/renderers/Renderer.cpp
Raspberry Pi 4 and later models are equipped dual HDMI out, so some people may be able to connect multiple displays and play games.
While there may be a minority using EmulationStation on Windows, there are many more who have multiple displays.
Therefore, I suggest adding the command line option `--monitor N`.
`N` is an integer specifying the display index. It defaults to 0, which is the current behavior. (The 0 origin is to match the SDL API.)
In addition, the option names and setting identifiers were based on Batocera.
=> Add new option --monitor

es-core/src/guis/GuiInputConfig.cpp
Both original Dualshock 4 and newly released Anbernic RG P01 aren't detected by the `filterTrigger` function.
With this, both triggers get registered as their respective positive axes.
Also considering that for some reason, the RG P01 has their triggers on axes 4 and 5 instead of 2 and 5.
=> Detecting DS4 and Anbernic P01 analog triggers

es-app/src/SystemScreenSaver.cpp, es-app/src/views/gamelist/ISimpleGameListView.h
these snippets accidentially haven't been removed (cf. #846).
duplicate code and `getPressCountInDuration()`  is member of CollectionSystemManager.cpp since then.
=> remove refactoring leftovers

CMakeLists.txt
Enable a version range to support both older and the new (4) versions of CMake. This mirrors the `pugixml` supported versions modified by the recent update.
CMake 3.5 is the minimum version, which seems quite reasonable given that:
- Debian Buster included version 3.14 (the Raspbian version includes `cmake` 3.16.3, which is what's included in our current image).
- Ubuntu 18.04 (now out of mainstream support) has `cmake` 3.10 included.
- RHEL 8 (and downstream Rocky/AlmaLinux/Centos) comes with `cmake` 3.11
Version 3.5 was released 9 years ago.
Closes #892
=> cmake: update supported versions
